### ISSUE TITLE
Azure Cosmos DB emulator for Cosmos Db Component

### ISSUE THREAD

**Issue by josephaw1022** [dotnet/aspire#1002]
**Related Issue:** #979
**Comment Reference:** [Issue #979 Comment](https://github.com/dotnet/aspire/issues/979#issuecomment-1821110496)

#### Description

After reviewing the discussion in issue #979 and the associated comment, I am seeking clarity on the current implementation status of the `UseEmulator` method for Cosmos DB in the Aspire project. My goal is to run the Cosmos DB emulator locally instead of relying on being able to connect to an Azure-hosted service. However, it's unclear if this functionality is supported.

#### Questions

1. **Current Implementation:**
   - Is the `UseEmulator` (or something along the lines of this) method for Cosmos DB already implemented in the project?
   - If so, can we go ahead and add queue it up to be in the aspire documentation?

2. **Approach for Implementation (If Not Yet Implemented):**
   - What would be the best approach to implement the `UseEmulator` method for Cosmos DB?
   - Which APIs would be prioritized for support? I assume the NoSQL API might be the first, but is there any plan to consider the MongoDB API as well?

#### Context and Rationale

- **Local Development:** The ability to use a Cosmos DB emulator is crucial for local development and testing, reducing dependencies on Azure's live environment.
- **API Support:** Understanding which APIs are considered for support will help in aligning development efforts and expectations.

**Comment by mitchdenny** [comment]
We've had some conversations with the Cosmos DB team in the background here and we think we might be able to get Cosmos DB to add support for a property on the connection string that instructs the client to ignore the emulator ceritifcate so that developers don't have to mess about with downloading and installing the cert or customizing the HTTP client properties for Cosmos themselves. I just created an issue in the .NET Cosmos DB library to track it:

https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4222

**Comment by mitchdenny** [comment]
We have an outstanding PR for this now (but the cert issue isn't solved yet):

https://github.com/dotnet/aspire/pull/1244
