### ISSUE TITLE
Support for Azure Web PubSub service

### ISSUE THREAD

**Issue by vicancy** [dotnet/aspire#1063]
- [x] Component support
- [ ] Provision support
- [ ] Advanced: Event handler support

**Comment by dersia** [comment]
I saw in the attached or that this was put on hold for signalR, but I have to say, that we decided to use WebPubSub, because it has much better client sdks outside the .NET world. so I would love to see this component.

I also think, that if this is added it should also bring the live traces experience that is available in the azure portal to the aspire dashboard.

**Comment by davidfowl** [comment]
Moving to 8.1

**Comment by eerhardt** [comment]
This is fixed with https://github.com/dotnet/aspire/pull/2495.
