### ISSUE TITLE
Add overload of AddProject that doesn't take an IServiceMetadata

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1065]
We should enable adding references to projects without the code generation of IServiceMetadata. This is possible today if you [manually create an `IServiceMetadata`](https://github.com/dotnet/aspire/issues/829#issuecomment-1826278967) but we should make that step easier.

```C#
public static IResourceBuilder<ProjectResource> AddProject(
    this IDistributedApplicationBuilder builder, string name, string projectPath);
```

As part of this nothing consumes `IServiceMetadata.AssemblyPath` nor `IServiceMetadata.AssemblyName`. We should consider removing those.

**Comment by DamianEdwards** [comment]
Hmm pretty sure I used `IServiceMetadata.AssemblyPath` and/or `IServiceMetadata.AssemblyName` in some of my samples or experiments. I'll have to try and find it and figure out why.

**Comment by davidfowl** [comment]
It's about to explode

**Comment by jonathanpickard3sq** [comment]
Thanks for adding multi-repo support via an Extension Method in Preview 2 (I'm going to be using multiple GIT repos, one per microservice and have a separate repo purely for the AppHost).

I've not been able to get the new extension method to work though: I get a runtime error as follows (I've copy/pasted an extract of the console output because one of the errors, Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0], repeats over and over again until I kill the console):

```
info: Aspire.Dashboard.DashboardWebApplication[0]
      Now listening on: http://localhost:15198
info: Aspire.Dashboard.DashboardWebApplication[0]
      OTLP server running at: http://localhost:16049
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      run session could not be started  {"Controller": "usvc-dev.developer.microsoft.com/executable-reconciler", "Executable": {"name":"scimtestmicroservice1-8di7vl8"}, "Reconciliation": 2, "State": "", "ExecutionID": "", "Status": "500 Internal Server Error", "Body": ""}
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\jonathanpickard\source\repos\ScimTestAspireHost\ScimTestAspireHost.AppHost
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      run session could not be started  {"Controller": "usvc-dev.developer.microsoft.com/executable-reconciler", "Executable": {"name":"scimtestmicroservice1-8di7vl8"}, "Reconciliation": 3, "State": "Starting", "ExecutionID": "", "Status": "500 Internal Server Error", "Body": ""}
fail: Aspire.Hosting.Dcp.dcpctrl.IdeExecutableRunner[0]
      failed to read message from IDE run session notification endpoint, stopping notifications processing      {"error": "websocket: close 1000 (normal)"}
fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      run session could not be started  {"Controller": "usvc-dev.developer.microsoft.com/executable-reconciler", "Executable": {"name":"scimtestmicroservice1-8di7vl8"}, "Reconciliation": 4, "State": "Starting", "ExecutionID": "", "Status": "500 Internal Server Error", "Body": ""}
```

This is the Program.cs in my AppHost:

```
var builder = DistributedApplication.CreateBuilder(args);

builder.AddProject("scimtestmicroservice1", projectPath: "../../ScimTestMicroservice1/ScimTestMicroservice1/ScimTestMicroservice1.csproj");

builder.Build().Run();
```

The App Host is referencing a very basic microservice web api in a completely separate directory that contains another Aspire solution.  So think of it like this: just for testing I have two Aspire Visual Studio solutions, each having an App Host, an API and Service Defaults projects.  If I attempt to get an AppHost to reference (via the new extension method) a project in the other solution then I get a runtime error.  If I use the extension method to reference an API within the same solution (using .csproj instead of TProject name) then I don't get an error.  It's as if Aspire doesn't like me using a project in a completely separate Visual Studio solution.

Any help is appreciated :-)

**Comment by jonathanpickard3sq** [comment]
Attached is a ZIP archive of the code that demonstrates the problem.  Open up ScimTestAspireHost.sln and run it.  You'll see the console open up and the error within.  Hope the code helps demonstrate the problem.
[AspireProblemSampleCode.zip](https://github.com/dotnet/aspire/files/13891625/AspireProblemSampleCode.zip)

**Comment by DamianEdwards** [comment]
@jonathanpickard3sq opened #1632 to track this, thanks.
