### ISSUE TITLE
GenerateAspireManifest target with value in AspireManifestPublishOutputPath errors out

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#1076]
When setting an `AspireManifestPublishOutputPath` property on the app host and running `dotnet msbuild /t:GenerateAspireManifest` the target fails

```
D:\AppCacheFiles\nuget\aspire.hosting\8.0.0-preview.1.23557.2\build\Aspire.Hosting.targets(118,5): error MSB3073: The c
ommand "..." exited with code -532462766. [D:\source\repos\AspireApp7\AspireApp7.AppHost\AspireApp7.AppHost.csproj]
```

**Comment by baronfel** [comment]
The path passed to `AspireManifestPublishOutputPath` currently needs to be a path-with-file-name in order to be successful. We should make this property a bit more flexible and support relative directories being passed in - if one is passed in then we should append `manifest.json` to it to get the final path.

We should also store the final computed value in another property - that would let users pass in a root value, call the target, and request the final property value all in one command so they can hardcode less information.
