### ISSUE TITLE
Add "Back to Traces" Navigation Button in Structured Logs View

### ISSUE THREAD

**Issue by josephaw1022** [dotnet/aspire#1180]
I've encountered two interrelated user experience issues while navigating the resource logs in our application.

1. **Lack of Back Navigation from Logs to Resource Page**: When I access the logs of a resource, there is no direct way to return to the specific resource page. This can be disorienting for users. To address this, I propose adding a back button with an accompanying query parameter. This would provide a straightforward way to navigate back to the resource page from the logs.

https://github.com/dotnet/aspire/assets/47674962/915b91d7-da84-48b0-8d21-3f5781413208

2. **Resetting of Filters on Using Browser Back Button**: Additionally, when using the browser's back button to return to the resource page from the logs, the state of any previously set filters (for resource types) is lost, requiring manual readjustment. This reset can be time-consuming for users.

While these could be logged as separate issues, their resolution is likely to involve related aspects of user navigation and state management in our UI. Addressing both in a cohesive manner would significantly enhance the overall user experience.

Similar to #1006

**Comment by tlmii** [comment]
Just noting that we have #1080 tracking a request similar to OP's 2nd bullet point (that issue tracks remembering the state of the various toggles in the details view, and this one is about the filter state - but they're both from a "remember state on a page" perspective).

> I propose adding a back button with an accompanying query parameter.

What information does this query parameter carry? Is it just an indication that you're going back to where you were, rather than starting fresh on the page (e.g. telling the page to load prior filter state)?

**Comment by JamesNK** [comment]
Back buttons have been removed. Should use the browser back button.
