### ISSUE TITLE
Structured log view doesn't include logger's category name

### ISSUE THREAD

**Issue by stephentoub** [dotnet/aspire#1200]
It'd be helpful if there were a way to get a column showing that in the dashboard.

**Comment by davidfowl** [comment]
cc @JamesNK

**Comment by JamesNK** [comment]
OTEL logging has the concept of scope. In .NET, this maps to the logger category name.

* Resource name (Aspire resource name)
  * Scope name (Logger category name)
    * Logs

Category name should definitely be added to the structured log details view. And be available to search on. Adding a new column is tricky because of finite screen real estate.

What should be smaller or given up to show the category name in the grid? (keep in mind that the grid needs to work well on smaller screens)

**Comment by JamesNK** [comment]
Done in https://github.com/dotnet/aspire/pull/1214. It isn't in the grid, just the details pane.

Re-open if this is important.

**Comment by En3Tho** [comment]
My personal preference is displaying LoggerName/Category/Whatever else right on the grid. Ideally it should be configurable of course but complex grid/details customization is a feature of it's own.
