### ISSUE TITLE
Azure postgresql

### ISSUE THREAD

**Issue by KSemenenko** [dotnet/aspire#1316]
I think this is also good option to create azure postgresql.
 
https://learn.microsoft.com/en-us/azure/postgresql/single-server/quickstart-create-server-database-portal

If I will do this contribution where i shoud start?

**Comment by danmoseley** [comment]
Have you looked at the readme in the components directory in this repo?

**Comment by KSemenenko** [comment]
Thanks a lot!

**Comment by mitchdenny** [comment]
Just a heads up, we are working with the AZD team on what the future looks like regarding provisioning managed database instances like Postgres (instead of using dev services addons). Its highly likely that the regular `postgres.server.v0` resource in the manifest will get translated into a Azure Postgres flexible server deployment so there would be no need for a custom Azure resource for this.

That said, there is room for a provisioner for Azure Postgres. But we need to do some more design work around the way our provisioner works.

**Comment by davidfowl** [comment]
This is done with preview 4 https://github.com/dotnet/aspire/issues/1960
