### ISSUE TITLE
Inconsistent trimming in column text between containers and resources

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/aspire#1385]
![image](https://github.com/dotnet/aspire/assets/350947/eba29cce-238e-4d6c-862e-4e1d1d7753a7)

- [ ] Containers are trimmed with ellipsis, while projects are truncated. We should make this consistent. The ellipsis seem preferable as they communicate that you're not seeing the full value.
- [ ] The project value seems to extend _outside_ of its cell to the right, encroaching on the state column.

![image](https://github.com/dotnet/aspire/assets/350947/85344c6f-f992-4523-ba2a-88ec4ef8f98f)

- [ ] The trimming seems over-zealous for containers. There's a bunch of unused space to the right of the ellipsis.

**Comment by drewnoakes** [comment]
There are inconsistencies between columns too:

![image](https://github.com/dotnet/aspire/assets/350947/fb71cf9e-ca3d-4a30-8fb0-6f111f301a45)

**Comment by tlmii** [comment]
> * [ ]  Containers are trimmed with ellipsis, while projects are truncated. We should make this consistent. The ellipsis seem preferable as they communicate that you're not seeing the full value.

Technically only the Container ID is getting the ellipsis treatment. If you shrink it even further, it'll start truncating when you get to the name.

> * [ ]  The project value seems to extend _outside_ of its cell to the right, encroaching on the state column.

Ignoring the lack of ellipsis, that's at least partially a weird artifact of the way the columns are laid out. The resize handle is actually part of the column header for the column to its left. You can sort of see it in this screengrab using browser dev tools:

![image](https://github.com/dotnet/aspire/assets/9613109/91917cb7-b402-4f73-81b0-7aebd17656c1)

So the grid cells below are the same width... but they go a lot further to the right than the resize handle.

> * [ ]  The trimming seems over-zealous for containers. There's a bunch of unused space to the right of the ellipsis.

That's mostly because of the (invisible in your screenshot) copy button. The button takes up space, it's not an overlay.

I'll take a quick look at these and see how easy it'd be to fix at least some of them.

**Comment by tlmii** [comment]
After playing with this for a while... it's going to be tricky. We get the ellipsis on the container ID almost by accident in this case. The GridValue component really isn't designed to be used next to something else in a grid cell. 

We can make it happen pretty easily for the projects by just getting rid of the FluentStack that wraps it. But there is [other commentary](https://github.com/dotnet/aspire/pull/1332#issuecomment-1854980696) about how it is weird to have the copy button for some things and not others in the same column (in that case its about the Source column, but same thing could reasonably apply here), and so if we did add that, it'd take away the easy fix for projects in this column.

**Comment by leslierichardson95** [comment]
@drewnoakes and @timli what's the status here?  Did we ever manage to resolve this issue?
