### ISSUE TITLE
Cannot use "." characters in resource names

### ISSUE THREAD

**Issue by weikanglim** [dotnet/aspire#1399]
With a AppHost:

```cs
var apiservice = builder.AddProject<Projects.name_ApiService>("api.service");
 
builder.AddProject<Projects.name_Web>("web.frontend")
    .WithReference(apiservice);
```
 
You get a manifest that looks like:
 
```json
"web.frontend": {
      "type": "project.v0",
      "path": "../name.Web/name.Web.csproj",
      "env": {
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES": "true",
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES": "true",
        "services__api.service__0": "{api.service.bindings.http.url}",
        "services__api.service__1": "{api.service.bindings.https.url}"
      },
```

Which fails infra generation since the dot character in the binding `api.service.bindings.http.url` is not escaped:

If you run `azd up`, you get an error that looks like:

`ERROR: generating infra/ folder: unknown resource referenced in binding expression: api`

**Comment by DamianEdwards** [comment]
I'm open to introducing restrictions on resource identifiers **as long as we author an analyzer for it at the same time**, so that the format validity can be seen directly in the editor as an error (and at build time too).

Based on some offline discussions, a suggested set of restrictions to start with might be:

- Limited to ASCII alphanumeric chars
- Must start with an alpha char
- Only special character allowed is hyphen (-) as a separator
  - ❓ Should we allow a trailing hyphen
  - ❓ Should we allow consecutive hyphens
- Must be between 1 and 64 chars total length
- Must be unique within the built app model
- Is case-insensitive (e.g. "api1" and "API1" are equivalent)

**Comment by mitchdenny** [comment]
Should we allow trailing hyphen ... no.
Should we allow consecutive hypens ... no.
Should we allow hyphens at all ... in my opinion .. no. The reason is that some resource types in cloud providers don't allow them.

We should consider forcing them all the lower case as well (also a constraint in some cloud providers).

**Comment by DamianEdwards** [comment]
> Should we allow hyphens at all ... in my opinion .. no. The reason is that some resource types in cloud providers don't allow them.

I think that's too restrictive of a baseline principal. Aspire doesn't itself map to any online cloud provider by itself and we shouldn't restrict resources to the union-set of all possible providers or even major providers. I think allowing a single separator char like hyphen in our resource names is required. If a given cloud platform doesn't support it for a given resource type, then the deployment tech should handle that translation.

**Comment by bradygaster** [comment]
Storage account names don't allow capital letters. Sorry to pile on!

**Comment by mitchdenny** [comment]
@JamesNK

**Comment by JamesNK** [comment]
> Only special character allowed is hyphen (-) as a separator

How often will resource names be used as an identifier in code gen C#? Hyphen isn't allowed in C# identifiers so a resource name can't be used to code gen a `my-cool-resource` property for example.

A valid alternative to hyphen is underscore. It is allow in C#.

> We should consider forcing them all the lower case as well (also a constraint in some cloud providers).

> Storage account names don't allow capital letters. Sorry to pile on!

If names are case-insensitive, then it doesn't matter if capitals are allowed or not. If the resource name needs to be used as a storage account name, then it can safely be converted to lowercase, e.g. `MyCoolResource` -> `mycoolresource`.

> Should we allow hyphens at all ... in my opinion .. no. The reason is that some resource types in cloud providers don't allow them.

If a cloud provider doesn't support hyphens, then they could be removed when generating names for that cloud provider. For example, `my-cool-resource` is converted to `my_cool_resource` (if underscores are allow) or `mycoolresource` if only alpha characters are allowed.

There could be conflicts between resources if there is `my-cool-resource` and `mycoolresource` because they resolve to the same name, but we can prompt with an error if that rare situation occurs.

**Comment by JamesNK** [comment]
What about other names in the model? For example, endpoints can have a name. Should they have the same restrictions?

**Comment by JamesNK** [comment]
What else has a name?
