### ISSUE TITLE
Validate experience in dashboard when server is unavailable

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/aspire#1554]
#1476 introduced a gRPC service to the app host, and client to the dashboard. That PR still has the components communicating in-process, just over a socket. Future work will move the dashboard to a separate process.

When that split happens, it will be possible that the client cannot connect to a server. We need to provide feedback about this.

Quick tests suggest the current experience is an empty resource page, with no error messages or indication that it's not connected.

**Comment by davidfowl** [comment]
The dashboard should also work when there's no resource server configured at all. In that mode it's just an OTLP server. 

cc @jamesnk for thoughts. Do we hide the resource tab in that case?

**Comment by drewnoakes** [comment]
Perhaps if no URL is passed as an environment variable, we don't even try to connect and hide resources.

Alternatively, we could show a "no resources available" message on the Resources page, along with a <kbd>Retry</kbd> button.

The `dotnet aspire-dashboard run` case should default to localhost on a given port.

**Comment by JamesNK** [comment]
> The dashboard should also work when there's no resource server configured at all. In that mode it's just an OTLP server.

These are different scenarios:
1. Dashboard is configured to have a resource server but can't call it.
2. Dashboard is configured not to have a resource server. I created a new issue for that [here](https://github.com/dotnet/aspire/issues/1556).

This issue is about scenario 1: dashboard has a server configured but can't call it. It's a UI question of how to display that status to the user. Related scenario is the dashboard has successfully loaded resources but then loses the connection (i.e. the background watch task breaks and can't be re-established.

Options:
1. Display a loading splash screen until the dashboard can connect to the server. Simple, but no one likes splash screens.
2. Display an error messages in the app:
  * Error message on the resources page. I don't think a retry button is necessary because the background watch task is automatically attempting to reconnect.
  * Also need an error message for the situation for when resources were loaded but the connection has been lost. We don't want to hide away resources we already have so this message could appear above or below the resource list.
  * What should happen to the application name in the UI if it can't be fetched?

**Comment by davidfowl** [comment]
This was fixed https://github.com/dotnet/aspire/pull/2199

**Comment by davidfowl** [comment]
We should file new issues with any follow up logic.
