### ISSUE TITLE
Console logs page fails to display logs if the selected resource is starting

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1582]
1. Start Aspire app
2. Quickly navigate to console logs page and choose a resource that is still starting

Once the resource has started:
* Expected result is the page shows console logs and status reports watching.
* Actual result is the page shows nothing and the status says it has finished watching.

Switching to another resource's logs then back again fixes the problem.

![console-logs-watch-starting](https://github.com/dotnet/aspire/assets/303201/fa3f584e-76ad-4274-85cf-c3e22782d305)

**Comment by davidfowl** [comment]
@karolz-ms Are we still implementing streaming logs in DCP?

**Comment by karolz-ms** [comment]
@davidfowl yes, that is still the goal. It has been delayed repeatedly by more urgent issues, but I want to get that done before GA

**Comment by tlmii** [comment]
What I'm seeing when the resource hasn't started yet is that the call to `DasbhoardClient.WatchResourceConsoleLogs` returns an `AsyncServerStreamingCall<WatchResourceConsoleLogsUpdate>` object as expected, but then `AsyncServerStreamingCall<WatchResourceConsoleLogsUpdate>.ResponseStream.ReadAllAsync(...)` returns an empty enumerator (or whatever else is needed to break the async foreach (it's not canceled as far as I can tell).

That ends the loop in `LogView.SetLogSourceAsync`, which ultimately gets us to:

https://github.com/dotnet/aspire/blob/66d14b17f6b7628efd6bc18bbbf1a0e71836b8c2/src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs#L202-L206

So it thinks things are done before they get started.

The question I guess is where should this be handled? Should whatever underlies the ReadAllAsync call be held open while it's starting? Or do we need to add some logic into the console logs page to handle it (perhaps wait until in a running state before starting the watch?). The latter seems maybe safer, but its not clear to me what the intent of the underlying system is.

I don't know much about the underlying implementation of that AsyncServerStreamingCall or even where it lives. I guess that's part of the grpc work that's new since I last looked at this code.  @JamesNK @drewnoakes for input on that side of things.

@karolz-ms would any changes here be mooted by the streaming logs in DCP? Or would the same issue still exist?

**Comment by karolz-ms** [comment]
@tlmii my guess would be that before the program has started, there is no log data available, so the request for logs terminates without returning any data.

I will make sure that in the new API, if the client requests the logs in "follow" mode, the server will start streaming the logs when they become available, no matter how early in the Executable lifecycle the client asks for them.

**Comment by JamesNK** [comment]
> @tlmii my guess would be that before the program has started, there is no log data available, so the request for logs terminates without returning any data.

It shouldn't work that way. The server should wait for logs. If the client wants to stop waiting, then that's up to it.
The server should only return if there is an unexpected error or the dashboard asked for logs for a non-existant resource.

**Comment by karolz-ms** [comment]
> It shouldn't work that way. The server should wait for logs. If the client wants to stop waiting, then that's up to it. The server should only return if there is an unexpected error or the dashboard asked for logs for a non-existant resource.

Agreed, but it does not do this today: https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting/Dashboard/ConsoleLogPublisher.cs#L29

**Comment by tlmii** [comment]
Is the `ConsoleLogPublisher` going to continue to be in use once the streaming log implementation is finished? In other words, is it worth fixing this now, or should we just close the issue (or mark it dependent on the streaming logs issue)?

**Comment by JamesNK** [comment]
As far as I know, it will be replaced by what @karolz-ms does in DCP. If the replacement is landing in P4 (or even P5) then we could leave it broken for now.

**Comment by karolz-ms** [comment]
Yes, that is the plan. To be quite honest, the part where we wait for the Executable to start may land in P5 not in P4. But it is definitively in scope for GA.

**Comment by JamesNK** [comment]
Let's close and re-evaluate once console logging is refactored.
