### ISSUE TITLE
Add background to the expander headers in the new resource details panel

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/aspire#1612]
A follow up suggestions to #1542 : 
https://github.com/dotnet/aspire/pull/1542#issuecomment-1882893982
https://github.com/dotnet/aspire/pull/1542#issuecomment-1883240381

Add a background to the expander headers for better section visibility.

**Comment by JamesNK** [comment]
The accordion originally had a lot more stuff to separate sections. Different background colors for headers, borders, etc. I turned it off because it didn't look good.

I've slightly increased the gap between each section (4px to 8px) to help highlight them:
![image](https://github.com/dotnet/aspire/assets/303201/91c3f222-c799-4720-9e37-a5d47d9be776)

**Comment by kvenkatrajan** [comment]
For example the background for each section header itself being a different color: 
![image](https://github.com/dotnet/aspire/assets/102772054/f56ead3d-5091-4aa1-a442-a0335628fc3b)
or indented
![image](https://github.com/dotnet/aspire/assets/102772054/a8e642d2-3a6a-48f7-bcf2-c3bb3afcbead)

**Comment by leslierichardson95** [comment]
I'm team indentation and different header color :)
