### ISSUE TITLE
[WebToolsE2E][Aspire] On the dashboard, click 'Console logs' twice, it shows 'An unhandled error has occurred Reload' on the page.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#1636]
**REGRESSION INFO**: Worked fine on Aspire template 8.0.0-preview.1 

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1 from [34509.254.main]
3. CLI workload update and install aspire 8.0.0-preview.3.24060.9
4. Apply NuGet Feeds

**REPRO STEPS**
1. In the VS, create a new project > ASP.NET Core Web API > .NET 8.0 > check 'Enlist in Aspire Orchestration' > Create
2. Build and Ctrl F5
3. In the dashboard, click 'Console logs', select web project。
4. Then click 'Console logs' again

**ACTUAL**
Clicking 'console logs' twice, it shows 'An unhandloed error has occurred' 
![issue1](https://github.com/dotnet/aspire/assets/82028229/d86c3652-a40b-40cf-bfa4-be39037cbb19)
![image](https://github.com/dotnet/aspire/assets/82028229/d8ed1d9c-3149-4bea-bfe0-13b55c9eb631)
**EXPECTED**
No error shows
![image](https://github.com/dotnet/aspire/assets/82028229/fccdd3b0-6c91-4e57-afd2-a6b656e7f5a5)

**Comment by kvenkatrajan** [comment]
Verified this occurs in the latest version.

**Comment by drewnoakes** [comment]
Exception fixed in #1677.

@v-cazhang I think there are actually two bugs here. My fix addresses the exception, but I also notice that your repro steps result in the same log output being displayed multiple times. With the exception fixed, the log is duplicated on each click. Here I clicked the "Logs" button two additional times. Each of the red boxes here contains the same content:

![image](https://github.com/dotnet/aspire/assets/350947/08e0712b-8477-4477-a582-1c7528fcb237)

I'm going to file a separate bug for this, but wanted to ask you whether this sequence of steps is in your test plan? If not, please be sure to add them. Thanks!

**Comment by v-cazhang** [comment]
@drewnoakes thanks for your kindly help, I will add this step into our future testing.

**Comment by drewnoakes** [comment]
The duplicate log bug is tracked in #1678.

**Comment by v-cazhang** [comment]
Verified on 17.10.0 Preview 1.0 [34522.204.main] + Aspire.ProjectTemplates.8.0.0-preview.3.24072.7, this issue and https://github.com/dotnet/aspire/issues/1678 both have been fixed.
