### ISSUE TITLE
[WebToolsE2E][Aspire] On the dashboard, the filter doesn't work after clicking 'Structured logs' again.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#1694]
**REGRESSION INFO**: Also repro on Aspire 8.0.0-preview.1.23557.2 and Aspire 8.0.0-preview.2.23619.3

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10.0 Preview 1.0 [34517.301.main]
3. Install Aspire Preview 3 latest build 8.0.0-preview.3.24067.3
4. Apply NuGet Feeds

**REPRO STEPS**

1. In the VS, create a new project > Aspire Starter Application > .NET 8.0 > Create
2. Ctrl + F5
3. On the dashboard, click 'Structured logs', select any project in the dropdown.
4. Click 'Structured logs' again.

**Notes**:

1. This issue also repro on 'Traces' board.

**ACTUAL**
The filter doesn't work after clicking 'Structured logs' again.
![issue1](https://github.com/dotnet/aspire/assets/82028229/dd7a1e44-f89d-456d-8b71-b2261461aeeb)

**EXPECTED**
Should work fine when clicking again.

**Comment by drewnoakes** [comment]
@adamint can you see if your recent fix addresses this bug too? Thanks.

**Comment by adamint** [comment]
It does not, this is a page that we don't persist state; this is actually the same issue as @tlmii ran into in #258; however, workaround Tim used in that PR does not work in this case. The same issue (display text not updating) occurs in the `Level` select component. @vnbaaij 

Since it was already being considered, a separate workaround would be to persist the structured logs filters @kvenkatrajan

**Comment by v-cazhang** [comment]
Verify on Aspire.ProjectTemplates.8.0.0-preview.4.24117.2, this issue doesn't repro on 'Structured logs' board, but still repro on 'Traces' board.
