### ISSUE TITLE
AddProject<TProject> with inferred name

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#1747]
AddProject has a generic `IServiceMetadata` argument. It is used to automatically set the project path. Have we considered also making the project name optional and getting it from the project file name?

Before:
```cs
builder.AddProject<Projects.MyFrontend>("frontend");
builder.AddProject<Projects.OrderProcessor>("orderprocessor");
builder.AddProject<Projects.ApiGateway>("apigateway");
```

After:
```cs
builder.AddProject<Projects.MyFrontend>(); // name is MyFrontend
builder.AddProject<Projects.OrderProcessor>(); // name is OrderProcessor
builder.AddProject<Projects.ApiGateway>(); // name is ApiGateway
```
If the name has underscores/dots then replace them with hyphens. We could also use something like Humanizer to turn pascal case names into lowercase + hyphen separated, e.g. `ApiGateway` -> `api-gateway`.

**Comment by davidfowl** [comment]
We decided against this in preview1 because the name is important to know, and the translation is not obvious. Also most .NET projects don't have simple names (and have lots of dots in then replaced by underscores). What we've seen in practice is that people rename the entire service. We don't want people renaming projects to make the names nice for service discovery...

**Comment by JamesNK** [comment]
Makes sense. Especially the side effect of renaming projects.
