### ISSUE TITLE
Container-like resource image tag management

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#1997]
We have a number of resources that use container images for the local inner loop (and also for production deployments via manifest). One of the challenges we have is how to approach which specific image is being used. In most cases this is captured in the `ContainerImageAnnotation`. To change the container image used you need to mutate/replace this annotation.

It would be good to provide a helper extension method on container-like resources to make this easier. For things that directly derive from `ContainerResource` (most non-cloud specific resources) we could just have a `WithImageTag(...)` method. This would take an enumeration such as `ImageTag.Latest` which when interpretted by the extension would set the tag to a `latest` tag.

Some containers might have more nuanced tagging strategies and so the extension method could be make more explicit for specific resources to make this mechanism easy for developers (with the escape hatch mechanism staying in place).

Related to all this is how we decide to update the default version. It might be that we always want to float to the latest, but tell customers that best practice is to pin to a particular tag once they have got things running to minimize disruption caused by accidental major version upgrades.

There are security implications of taking the latest and there are security implications of not picking up updates. Additionally we don't have a mechanism at the moment to force a pull of a container image from an upstream source. Once it is in the local Docker daemon cache - perhaps this is something that DCP should manage (cache refreshes).

/cc @davidfowl @karolz-ms @blowdart @joperezr

**Comment by karolz-ms** [comment]
In my opinion, for development time we should allow users to use ANY image they want for a given component, and not just restrict the customization ability to tag changes. There are many scenarios where using a custom image is beneficial or required. For example, it might be a company policy to only used "blessed" images from company image registry. Or the developer might want to add some additional debugging tools to the image.

Granted, this is somewhat more advanced scenario and there might be issues with custom images, but that is not a reason strong enough to not allow completely custom images.

I agree that using specific image version/tag, instead of "latest", generally leads to less trouble.

As for stale image checks, we have prior art for that in our VS/VS Code container extensions. We could have the AppHost or DCP could do a similar staleness check in the background and emit warnings during the application run if stale images are detected.

**Comment by eerhardt** [comment]
I think we should make 3 changes here:

1. Allow the developer to pick the tag.
    - As discussed above with an API, or using the AppHost configuration to map container resource names to tags.
2. Allow the developer to pick the registry.
    - Some enterprises don't allow devs to use images from docker hub and want their own registry for security reasons. Just like how we don't use nuget.org in our repo.
    - I imagine us having this at 2 levels:
        - Developers can pick the registry for each image, just like they can pick the tag.
        - A global default that is used when no registry is specified on the individual image. And using docker hub (i.e. what we do today) when the global default isn't set.
3. Stop using `latest` by default and instead use the minor version of a tag, allowing for floating patches.
    - Today we are running the risk of picking up new major versions of the image, which may contain breaking changes.
    - We plan on shipping Aspire monthly, so when new container versions come out we can update our code to use the new version. This allows us to ship depending on the same versions of containers that we tested against. This is similar to how we plan on updating/servicing for Components' dependencies.
    - If the image owner follows semantic versioning and does tagging similarly, their security patches will automatically get used.

> As for stale image checks, we have prior art for that in our VS/VS Code container extensions. 

I like this plan. I don't want customers to pay the cost on every F5.

**Comment by mitchdenny** [comment]
Related #2220

**Comment by mitchdenny** [comment]
@eerhardt take a look at what merged in with: https://github.com/dotnet/aspire/pull/2179

**Comment by eerhardt** [comment]
>  mitchdenny closed this as completed in #2224 4 days ago

Have we done the work for:

1. Allow the developer to pick the tag.
2. Allow the developer to pick the registry.

?
