### ISSUE TITLE
RabbitMQ logs ex.Type / ex.StackTrace, etc instead of standard otel exception.type, exception.stacktrace

### ISSUE THREAD

**Issue by adamint** [dotnet/aspire#2118]
See [here](https://github.com/dotnet/aspire/pull/2087#discussion_r1479125450) 

cc @Erarndt

**Comment by eerhardt** [comment]
The reason it used the current names (as far as I can remember) is because the RabbitMQ EventSource it listens to names this information `"ex"`.

https://github.com/dotnet/aspire/blob/f2d158bf2b02e370a6c0714313823e5a612ab962/src/Components/Aspire.RabbitMQ.Client/RabbitMQEventSourceLogForwarder.cs#L136-L159

So it was just using the underlying names the EventSource information was given.

We can turn these into standard OTel names if that is the agreed upon format.

**Comment by davidfowl** [comment]
Yes please!

**Comment by JamesNK** [comment]
While we've here, RabbitMQ appears to put all the exception details in the message. Can it just be the exception message?

**Comment by eerhardt** [comment]
> While we've here, RabbitMQ appears to put all the exception details in the message. Can it just be the exception message?

This will need to be fixed in the RabbitMQ.Client library itself. I've opened https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/1493 for it. The latest 6.x version has better exception formatting (it still shows the full exception to string in the Message however). I've opened https://github.com/dotnet/aspire/pull/2159 to update to the latest.
