### ISSUE TITLE
AddRabbitMQ method with volume mounts does not persist queues across restarts by default

### ISSUE THREAD

**Issue by pedershk** [dotnet/aspire#2247]
RabbitMQ uses its HOSTNAME to set up paths for queues on its internal storage. As the DCP generates a random hostname across restarts, this changes with every invocation of the container. This results in unexpected behavior from the developer's point of view - queues are not persisted across restarts even with persistent storage configured for the container.

This is an example of a statement that will NOT persist queues:

```
 var rabbitMq = builder
     .AddRabbitMQContainer("rabbitmq-host", 5672, password: rabbitMqPassword)
     .WithVolumeMount("rabbitmq-host-vol", "/var/lib/rabbitmq", VolumeMountType.Named);
```

If a NODENAME environment variable is set, RabbitMQ uses that to override the HOSTNAME on the container for internal configuration purposes. So directly specifiying the NODENAME variable With i.e. `WithEnvironment("NODENAME", "rabbit@localhost")` resolves the issue, as in the following statement:

```
 var rabbitMq = builder
     .AddRabbitMQContainer("rabbitmq-host", 5672, password: rabbitMqPassword)
     .WithEnvironment("NODENAME", "rabbit@localhost")
     .WithVolumeMount("rabbitmq-host-vol", "/var/lib/rabbitmq", VolumeMountType.Named);
```

Suggestion : set NODENAME by default to a fixed value for RabbitMQ hosts (it's only used internally, so won't affect other RabbitMQ containers running in the same docker engine) - but still allow the user to override by setting it specifically like above. Alternatively, as a minimum, update the RabbitMQ container documentation for Aspire to mention this specifically.

**Comment by eerhardt** [comment]
@mitchdenny - what do you think about having a "UsePersistence()" extension method in RabbitMQ that does this? Similar to the Storage container:

https://github.com/dotnet/aspire/blob/98950280f176b5908fc985fe441d9d7a6ae84ae7/playground/AzureStorageEndToEnd/AzureStorageEndToEnd.AppHost/Program.cs#L6-L9

**Comment by mitchdenny** [comment]
Need to think it through all the way to deployment, but definatley open to this idea. The difference between this and the storage resource is that Rabbit MQ is already a container so no need for the callback.

**Comment by joperezr** [comment]
@mitchdenny were you planning on taking this one according to the above?

**Comment by davidfowl** [comment]
@sebastienros assigning this to you. There's work to add helpers for containers for persistence, you might be able to build on top https://github.com/dotnet/aspire/pull/1317

**Comment by davidfowl** [comment]
@DamianEdwards does this work now?

**Comment by DamianEdwards** [comment]
Let me try it out.

**Comment by DamianEdwards** [comment]
Ok an update. I tried the scenario out with the new `WithDataVolume()` method and can confirm what @pedershk reported that Redis internally lays out storage based on the node name which in the case of a changing port is not stable, so using a volume just results in a new sub-dir structure being created in it each time. I updated the `WithDataVolume()` and `WithDataBindMount()` to set a stable node name via the `RABBITMQ_NODENAME` environment variable ([docs](https://www.rabbitmq.com/docs/configure#supported-environment-variables)) and that indeed resulted in the same directory being used each time, but then a stable password is required (logins fail otherwise, same as #1151). So I created a stable password via a parameter and then ran into issues with password escaping in the connection string (#3117) which I worked around.

I then set about trying to create the scenario where message are enqueued but not consumed in one dev session, and then in the next dev session they are consumed, but I haven't been able to do so. I used the TestShop app to do this as it already has separate projects that produce and consume messages, so once modified to use persistence for RabbitMQ, I can just start a dev session with the resource that consumes messages (`orderprocessor`) commented out, add some items to the basket and then click the basket to force an order to be created and thus a message produced. Then stop the session, uncomment the resource, then start a new dev session. I'm expecting to see the `orderprocessor` receive the unprocessed messages when it starts but it does not. The logs for the RabbitMQ container seem to indicate that no queue restoration took place when it started.

My changes so far are in https://github.com/dotnet/aspire/tree/damianedwards/rabbitmq-volume

@pedershk any thoughts on what might be going on?

**Comment by pedershk** [comment]
Hi @DamianEdwards. I've observed the same behavior with passwords - this forced me to not use persistence with RabbitMQ when developing locally (we use ASB in our deployed test environment, so not an issue there). I was a bit flummoxed that the password parameter was removed from the `AddRabbitMQ` method, to be honest - what's the reasoning behind this change? I understand it can be set via a parameter now, but it's not at all obvious - and the sum of this makes it hard to hook up things like the RMQ admin interface.

I haven't set the password to a fixed value, so haven't been able to observe the non-stateful behavior you've been seeing. I CAN confirm however that previously, when password was being set via the `AddRabbitMQ` method parameter, persistence was working properly and queues persisted across restarts with the addition of the `RABBITMQ_NODENAME` environment variable to the container.

Sorry I can't be of more help - but it would be good to get this back in a functional state.

**Comment by davidfowl** [comment]
> I was a bit flummoxed that the password parameter was removed from the AddRabbitMQ method, to be honest (atleast in P4 - I'm not currently using nightlies) - what's the reasoning behind this change? I understand it can be set via a parameter now, but it's not at all obvious - and the sum of this makes it hard to hook up things like the RMQ admin interface.

P4 still had lots of inconsistency. When we unified the container-based methods, we didn't add the password configuration back and that was an oversight. It lead to [this issue](https://github.com/dotnet/aspire/issues/2403) which we resolved in P5.

**Comment by DamianEdwards** [comment]
@pedershk I'm completely new to RabbitMQ so it's possible I'm doing something wrong. Can you look at the code in the [TestShop.BasketService (producer)](https://github.com/dotnet/aspire/blob/a5fdb9b0d2b600e6dd92e6baddde99b50263dd21/playground/TestShop/BasketService/BasketService.cs#L70) and [TestShop.OrderProcessor (consumer) projects](https://github.com/dotnet/aspire/blob/a5fdb9b0d2b600e6dd92e6baddde99b50263dd21/playground/TestShop/OrderProcessor/OrderProcessingWorker.cs) and confirm that the code, coupled with the procedure I documented above, should be sufficient to test the scenario?

**Comment by pedershk** [comment]
> @pedershk I'm completely new to RabbitMQ so it's possible I'm doing something wrong. Can you look at the code in the [TestShop.BasketService (producer)](https://github.com/dotnet/aspire/blob/a5fdb9b0d2b600e6dd92e6baddde99b50263dd21/playground/TestShop/BasketService/BasketService.cs#L70) and [TestShop.OrderProcessor (consumer) projects](https://github.com/dotnet/aspire/blob/a5fdb9b0d2b600e6dd92e6baddde99b50263dd21/playground/TestShop/OrderProcessor/OrderProcessingWorker.cs) and confirm that the code, coupled with the procedure I documented above, should be sufficient to test the scenario?

Afraid I'm not going to be much help - I've only ever used RabbitMQ through abstractions such as MassTransit. But I'm not entirely sure that the C# SDK creates queues with persistence by default - RabbitMQ also has non-persisted queue types. 

MassTransit creates queues with persistence by default, however.

I can download a nightly build of Aspire and test with your AddRabbitMQ in the TestShop Apphost against my own MassTransit code - but that may not be sufficient to validate your scenario?

**Comment by DamianEdwards** [comment]
That was it! Confirmed it's working now. I'll send a PR.

![image](https://github.com/dotnet/aspire/assets/249088/b6091f58-bffc-4814-a205-8e059ce22144)

![image](https://github.com/dotnet/aspire/assets/249088/20bc6854-159a-4ca6-be21-4ef912c90918)

**Comment by davidfowl** [comment]
@DamianEdwards can you backport

**Comment by DamianEdwards** [comment]
@davidfowl https://github.com/dotnet/aspire/pull/3186
