### ISSUE TITLE
Row background highlighting on mouse hover

### ISSUE THREAD

**Issue by malisancube** [dotnet/aspire#2281]
May you add a highlight on mouse hover for the grids. Its a bit dificult to focus on the row. More like the list we have here on github for filling issues.

**Comment by tlmii** [comment]
Status update here: 

Currently there are no color tokens for `-hover` for the `--neutral-layer-*` backgrounds that we use for the layers in the site. The included hover state (`--neutral-fill-hover`) works ok for the main grids in dark mode, barely for the main grids and details grids in light mode and not at all for the details panel grids in dark mode. 

Working with the fluentui folks and @vnbaaij to see how easily we can create new recipes based on our layers and use them. Otherwise I'll find some values that work and hardcode them.

**Comment by tlmii** [comment]
The changes needed to be able to create our own design tokens are working their way through, starting here: https://github.com/microsoft/fluentui/pull/30784. Will need to be brought into the blazor components first then we can start using it.

**Comment by kvenkatrajan** [comment]
Moving to 8.1. @tlmii  had a look might take some new javascript work to make it work and additional testing - probably safer to move it to after GA.
