### ISSUE TITLE
Dashboard page navigation shortcuts run on multiple browser windows

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2467]
1. Open another browser window for the dashboard
2. Hit `c` then `t`. Both browser windows go to each page

Only the focused browser window should be impacted by shortcuts.

This doesn't appear to impact some shortcuts. e.g. `shift-x` to close a panel only runs on the focused browser window.

![dashboard-shortcut-multiple-windows](https://github.com/dotnet/aspire/assets/303201/a84a6a7a-b179-4f37-b4e3-eda3544e714c)

**Comment by JamesNK** [comment]
Close pane is fine:

![dashboard-shortcut-multiple-windows-close-pane](https://github.com/dotnet/aspire/assets/303201/61108ac5-b014-4c35-af0b-29382f291757)

We should figure out why some are good and others are bad, or double check each shortcut.

**Comment by tlmii** [comment]
Close pane actually does get triggered on multiple windows, but the handling of it actually leads to an exception that gets eaten and so its not obvious that it gets executed.

It seems like the issue is that ShortcutManager is static, so the handlers apply across all pages. That probably needs to be injected and circuit-scoped.
