### ISSUE TITLE
allow overridding of default annotations

### ISSUE THREAD

**Issue by gabriel-systems** [dotnet/aspire#2486]
In some cases the default annotation for a resource/container needs to be overridden and this currently requires replacing/rewritting a lot of code, when a simple replacement of one or more of the resource annotations is all that is required.  please consider a way to remove/replace/list annotations attached to a resource builder.

**Comment by davidfowl** [comment]
Can you give examples of what you are trying to accomplish?

**Comment by 3GDXC** [comment]
@davidfowl when using the builder.Add{service}Container() or other extension methods as provided by 3rd party it may not allow the developers to override the repository, image or tag and/or replace default annotation values. It would be great if the values could be changed prior to building of the container via a  delegate or configuration item using a fluent style syntax (extension methods) and or query annotations using linq style methods to make complex code base decisions.

buider.AddRedisContainer(name:"redis",password:"something")

.UsingRepository("localRepository")
.UsingImage("")
.UsingTag("")

.RemoveEndpoint(name: "management")
.RemoveEndpoint(name: "debug", (annotations)=>
{ 
return annotations.Any(a=>a.TypeOf(EndPointAnnotation) && a.Protocol == Tcp && uriSchema == "https")
})

**Comment by davidfowl** [comment]
In preview 4 and 5, there are higher level methods that allow changing the container properties. There are also methods for changing endpoints. If you have more suggestions for methods that we should add I would enumerate them and then we (or others) can iterate on the design of those APIs and then accept PRs. 

This issue is a bit broad (more of a discussion) so it's not very actional in its current state.
