### ISSUE TITLE
Dashboard resources page displays green tick for empty status

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2557]
Resources are initially provided to the dashboard with no status. That very quickly changes to `Starting`. However, if you have 100s of resources, it takes a while to start them all. Many wait with no status but have a green tick.

Either no icon should be displayed if the status is empty, or a grey circle (like what `Starting` has)

**Comment by MatsM16** [comment]
@JamesNK  
I can think of two options:
A: Assume a new resource eventually becomes `ResourceStates.StartingState` and display as `Starting`.
B: Make a new state `ResourceStates.PendingState` and make this the default state.
C: Render nothing when `Resource is { State: null }`

I prefer option A because it requires less change than B and is less confusing for the user than C.  
*Option A:*
```diff
- else if (Resource is { State: ResourceStates.StartingState })
+ else if (Resource is { State: ResourceStates.StartingState or /* pending */ null })
```

**Comment by JamesNK** [comment]
I don't think we should assume a Starting status in the dashboard. If we wanted the status to always be starting initially then we'd set that in the data given to the dashboard, rather than assume in the dashboard UI.

Option C please.
