### ISSUE TITLE
Dashboard loading indicator

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2568]
The dashboard loads data pretty quickly, but there is still a brief moment of time when it displays a message that no data is available. For example, if you visit the resources page then it shows "No resources found" for a brief amount of time before displaying resources. In cloud environments, there might be a longer delay for the resource service to return values.

We don't want to display "No resources found" while people wait. That's confusing. Instead, there should be a loading indicator and the text "Loading" until either data is returned, or it's confirmed no data is available, at which point it's correct to show a "No resources found" message.

Loading indicator (spinning circle + "Loading" text) should be added to a number of pages:

* Resources
* Structured logs
* Traces
* Metrics (maybe, after a resource is selected but before meters and instruments are available)

See images at https://github.com/dotnet/aspire/pull/2556 as an example.

**Comment by JamesNK** [comment]
FluentDataGrid has a loading flag and template - https://www.fluentui-blazor.net/DataGrid

**Comment by tlmii** [comment]
In my testing we need to wait for this fix: https://github.com/microsoft/fluentui-blazor/pull/1512 before this will work properly for us. I'm not quite ready to move to a build that has that yet, so will hold off briefly.

**Comment by JamesNK** [comment]
> I'm not quite ready to move to a build that has that yet, so will hold off briefly.

What do you mean? I created a PR to update to a preview version with some fixes that I requested: https://github.com/dotnet/aspire/pull/2691

**Comment by tlmii** [comment]
> > I'm not quite ready to move to a build that has that yet, so will hold off briefly.
> 
> 
> 
> What do you mean? I created a PR to update to a preview version with some fixes that I requested: https://github.com/dotnet/aspire/pull/2691

Primarily was #2683 which already merged. Also I remember what happened last time we tried to update and I wanted to take a moment to use it before updating and didn't have time right then.

**Comment by tlmii** [comment]
I think it'd help to define where in the data flow for each of these pages we want the loading indicator to be displayed. For instance here's a stab at it for resources page:

1. The page starts with Loading = true
2. The loading indicator will be displayed while things are getting setup and while the call to SubscriberResourcesAsync is awaited and the snapshot results are parsed
3. Loading is set to false 
4. If there were no resources at that point, No resources found will be displayed, otherwise the actual resources will be displayed
5. Its possible that no resources are found initially and then eventually some appear.

I think 5 is a little weird, but we have no way to confirm that no resources will _ever_ show up as far as I'm aware. So it seems reasonable that we'd say no resources if the initial load didn't contain any and then adjust in the future accordingly. But I can see the argument that that'd still be confusing in particularly slow environments.

I've got the above working fine now that we have the fix I mentioned in a prior comment.

But for the other pages, its less clear to me how we do that because of how the underlying repositories are (generally) already populated and ready by the time the page loads. The view model just provides the requested span of data from the underlying shared telemetry repository. It doesn't seem like there's much, if any, delay between page load and the first render of (possibly empty) data where we should show the loading indicator. But I'm happy to be pointed to something that we could use as an indicator of readiness. 

@JamesNK since you probably have the most thoughts on Structured Logs, Traces and Metrics.
