### ISSUE TITLE
how to reach enviroment variables in Blazor Webassembly In Aspire

### ISSUE THREAD

**Issue by wisamidris7** [dotnet/aspire#2624]
I encountered an issue while developing a simple WebAssembly (Wasm) OpenID application. When passing the variables, the code looked like this:

```c#
webApp.WithEnvironment("OpenIdConnect:Authority", idpHttps);
webApp.WithEnvironment("OpenIdConnect:RedirectUri", 
    Path.Combine(webApp.GetEndpoint("https").UriString, "authentication/login-callback"));
webApp.WithEnvironment("OpenIdConnect:PostLogoutRedirectUri",
    Path.Combine(webApp.GetEndpoint("https").UriString, "authentication/logout-callback"));
```

However, when configuring the application, an exception was thrown indicating that no authority was provided. It seems that the environment variables were not passed correctly. I suspect that WebAssembly does not have direct access to environment variables.

Now, I'm wondering if I have to manually put the links or if there is another way to access the variables. Can anyone provide guidance on how to resolve this issue? Any help would be greatly appreciated. Thank you!

**Comment by mitchdenny** [comment]
@wisamidris7 is your WASM application Blazor?

The web assembly application definately does not have access to the environment variables on the server it was loaded from, its completely sandboxed. Any configuration information you want in the web assembly application will need to be passed to it from the server via a HTTP request. Of course you'll want to be very careful what information that is especially since we are talking about authentication scenarios here.

**Comment by wisamidris7** [comment]
Thanks i was only talking for openid url
