### ISSUE TITLE
[WebToolsE2E][Aspire] There is no intellisense of 'Parameters' in the appsettings.json file.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire#2636]
**REGRESSION INFO**: New feature on Aspire 8.0 Preview 4

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.10.0 Preview 2.0 [34701.141.d17.10] (Includes Aspire 8.0.0-preview.4.24129.7)
3. Apply NuGet Feeds

**REPRO STEPS**

1. New Project > ASP.NET Core Empty project > 8.0 > check 'Enlist in Aspire Orchestration'
2. Right-click empty project > Add > Aspire component > install Aspire.Azure.Security.KeyVault
5. In the appsettings.json file of the empty project, type "" in the top of the file.

**Notes**:

1. It will meet [Bug 1985774](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1985774) when adding the aspire component.

**ACTUAL**
No intellisense of 'Parameters' shows
![image](https://github.com/dotnet/aspire/assets/82028229/d033ceb4-5884-4337-83d6-ff50558c6383)

**EXPECTED**
Should contain 'Parameters' in the intellisense

**Comment by DamianEdwards** [comment]
@eerhardt do we need to update the schema generator?

**Comment by eerhardt** [comment]
> @eerhardt do we need to update the schema generator?

This isn't the schema generator. Note that nothing in the web app uses the `Parameters` config section.

The thing that reads the `Parameters` config section is the app host.

https://github.com/dotnet/aspire/blob/914760c2ebb56f107c9f37136597fb7a57c2d365/src/Aspire.Hosting/ParameterResourceBuilderExtensions.cs#L27-L28

https://github.com/dotnet/aspire/blob/914760c2ebb56f107c9f37136597fb7a57c2d365/src/Aspire.Hosting/ParameterResourceBuilderExtensions.cs#L43-L46

So if anything, we could ship a new JSON schema in `Aspire.Hosting.AppHost` that adds this section to the appsettings.json schema.

**Comment by DamianEdwards** [comment]
Ah of course, thanks. Putting on the backlog for now.

**Comment by vladimir-shirmanov** [comment]
Hello, @eerhardt 
I would like to contribute, but not sure what I should do here.
My idea, as you said, is to add aspire-8.0-host.json schema to https://github.com/dotnet/aspire/tree/main/src/Schema folder.
But it could require publishing it to https://www.schemastore.org/json/ as well.
Plus, I'm not really sure what this Parameters property should be and do I need to copy https://json.schemastore.org/appsettings.json to this full schema. 
I would really appreciate your thoughts on this one. Thank you in advance

**Comment by eerhardt** [comment]
Thanks for your interest @vladimir-shirmanov.

https://github.com/dotnet/aspire/discussions/963 describes a bit for how the JsonSchemaSegment MSBuild Item works. The general approach to fix this issue is to:

1. Create an `AspireAppHostConfiguration.json` file under https://github.com/dotnet/aspire/tree/main/src/Aspire.Hosting.AppHost. This file contains the appsettings JSON schema (for example, the "Parameters" section).
2. Ensure this file is packed into the root of the `Aspire.Hosting.AppHost` nuget package.
3. In https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.AppHost/buildTransitive/Aspire.Hosting.AppHost.targets, add the following MSBuild logic:

```xml
  <ItemGroup>
    <JsonSchemaSegment Include="$(MSBuildThisFileDirectory)..\AspireAppHostConfiguration.json"
                       FilePathPattern="appsettings\..*json" />
  </ItemGroup>
```

When VS sees this `JsonSchemaSegment` in a nuget package, it will automatically combine the segment into the larger appsettings.json Intellisenseschema file.

For extra credit (if you are feeling ambitious), you could do the same for https://github.com/dotnet/aspire/tree/main/src/Aspire.Hosting.Azure and add a JSON schema for [these properties](https://github.com/dotnet/aspire/tree/main/src/Aspire.Hosting.Azure#configure-azure-provisioning-for-local-development):

* `Azure:SubscriptionId`
* `Azure:ResourceGroup`
* `Azure:ResourceGroupPrefix`
* `Azure:AllowResourceGroupCreation`
* `Azure:Location`
* `Azure:CredentialSource`

See https://github.com/dotnet/aspire/blob/681f2e754dc849f96abafcd2829783e69155abf1/src/Aspire.Hosting.Azure/Provisioning/AzureProvisionerOptions.cs#L8-L28
*

**Comment by vladimir-shirmanov** [comment]
Hello @eerhardt,

I raised a PR, will really appreciate any feedback and comments,

thank you in advance

**Comment by vladimir-shirmanov** [comment]
Hello, can someone please review the PR, @eerhardt I made improvements that you recommended
