### ISSUE TITLE
Python Support in Aspire

### ISSUE THREAD

**Issue by dorgrin6** [dotnet/aspire#2760]
Hey team,

I’ve been exploring Aspire, and it’s impressive! But here’s the thing: Python support is a must for us. Many data science teams, including ours, rely on Python containers. Since [Visual Studio already supports Python](https://visualstudio.microsoft.com/vs/features/python/), adding it to Aspire would be a game-changer.

Cheers.
@davidfowl  - FYI

**Comment by En3Tho** [comment]
@dorgrin6 What do you mean by supporting Python?

There could be multiple things:
1) Running python based apps natively like with Node support?

2) ServiceDiscovery package for Python?

3) A whole separate Aspire.Python package which imitates behavior of Aspire but for Python?

I think you can easily hack together 1 and 2 and see how it goes.

As for 3 I don't think there is a need for this kind of thing - Python community can easily do the thing themselves.

I guess Node native support is a must because .Net backend + js/ts + node frontend is standard thing. I can't say the same for Python + .Net honestly.

**Comment by dorgrin6** [comment]
I meant 1 & 2.
I'll try to hack this together as proposed.
Would node integration be a good example for this?

**Comment by mitchdenny** [comment]
@dorgrin6 in terms of 1 & 2 I'd be interested in seeing a PR for Aspire. I think item 3 is probably a different open source project entirely.

**Comment by wmeints** [comment]
I'm working on a separate package for Python support. https://github.com/wmeints/aspire-python

**Comment by wmeints** [comment]
Turns out there are a couple of limitations for extending the hosting bits outside of the main repo.
Testing is harder because you need to build your own testing infrastructure. Which involves copying over quite a lot of code.

So instead of building my own package, I propose to use my PR that I submitted.

**Comment by mitchdenny** [comment]
Python support is almost certainly something we'd want to support in-tree anyway since its pretty common in things like AI scenarios.

**Comment by mitchdenny** [comment]
There is a meta conversation here which is not Python specific about how we want to handle closely related application frameworks:

https://github.com/dotnet/aspire/issues/4163

Interesting for Node.js we don't have APIs which are specific to say ExpressJS?

**Comment by Meir017** [comment]
*fixed by #4142
