### ISSUE TITLE
ClassLib cannot be used in AppHost in p2p references (even with setting)

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire#2769]
I don't think `IsAspireProjectResource=false` is working properly?

Repro:
1. Create an aspire-starter app
2. Create a class lib (ClassLibrary1) (add a single method SayHello())
3. In class lib add `<IsAspireProjectResource>false</IsAspireProjectResource>`
4. Add a reference to ClassLibrary1 from AppHost

EXPECT: Be able to use ClassLibrary classes and methods
ACTUAL: IProjectMetadata still generated for this class lib and not able to find/use Class1

When packaged as nuget package, no problems.

**Comment by davidfowl** [comment]
You add it to the project reference in the apphost, not the project

**Comment by timheuer** [comment]
I don't understand, this is what I did (added it to project reference in the apphost) as I mentioned.

AppHost -> ref to ClassLibrary1 project (which has `IsAspireProjectResource=false`).  It results in still treating it as IProjectMetadata.

**Comment by davidfowl** [comment]
It’s the tradeoff we made wrt the app host and service projects. Ideally we would default class libs to be normal project refs and executables to be service projects.

I think we are unable to determine the project type early enough accomplish this.

cc @eerhardt @baronfel

**Comment by eerhardt** [comment]
> I think we are unable to determine the project type early enough accomplish this.

This is correct. In order for this to really work we need to determine the project type before restore happens.

The only other viable option here is to not use `ProjectReference` for the `AppHost` => `Service Apps` references. We decided not to take that approach because it would cause tooling changes. But we can revisit that decision if the current model is too confusing.

**Comment by timheuer** [comment]
We should convert this issue to revisit the design and/or visit new tooling experiences.  At present the natural paths for tools (CLI + ecosystem) don't enable this well.  And maybe it doesn't matter to solve here (e.g. is this a problem that non-aspire project references are going to be in apphost enough to solve)

**Comment by eerhardt** [comment]
To be clear: the "only other viable redesign option" is:

```xml
  <ItemGroup>
    <ProjectReference Include="..\AspireStarterApplication.1.ApiService\AspireStarterApplication.1.ApiService.csproj" />
    <ProjectReference Include="..\AspireStarterApplication.1.Web\AspireStarterApplication.1.Web.csproj" />
  </ItemGroup>
```

becomes

```xml
  <ItemGroup>
    <AspireProjectResource Include="..\AspireStarterApplication.1.ApiService\AspireStarterApplication.1.ApiService.csproj" />
    <AspireProjectResource Include="..\AspireStarterApplication.1.Web\AspireStarterApplication.1.Web.csproj" />
  </ItemGroup>
```

(naming TBD)

So every time you want to add a new "service app" project, you need to manually add `AspireProjectResource` in your .csproj until we add some sort of tooling support for this. Note that VS will need to be updated to emit `AspireProjectResource` items instead of `ProjectReference` items where it does today for "Enlist in Aspire Orchestration".

And then "normal" `ProjectReference` items work like normal for the AppHost.

> visit new tooling experiences

One option here is that when you "Add Project Reference" in VS (like drag-n-drop), and the project is an Aspire AppHost, VS emits `<ProjectReference Include="..." IsAspireProjectResource="false" />`. So that way this "just works" for people in VS.

**Comment by mitchdenny** [comment]
The downside of the alternative to what we have now is that command-line experiences also need to change also.

**Comment by davidfowl** [comment]
This is by design.
