### ISSUE TITLE
Console logs: always underline URLs

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2841]
AZDO always underlines URLs in console output:
![image](https://github.com/dotnet/aspire/assets/303201/24f59be9-0bee-4aa3-9b0c-5df6f50a3312)

GitHub actions always underlines URLs in console output:
![image](https://github.com/dotnet/aspire/assets/303201/5f8209cf-0ad3-4657-92ed-5740efbefa5d)

Aspire currently **doesn't** (underline appears on mouse over):
![image](https://github.com/dotnet/aspire/assets/303201/d3ebd03f-4dc3-4206-8167-e78ce81ccd2a)

IMO Aspire console logs should follow the crowd and underline detected URLs.

**Comment by tlmii** [comment]
I don't particularly like it - I think the underline makes the text too busy and harder to read. 

The fact that we only support URLs as links (as opposed to otherwise plain text like on a normal page) means you can already visually tell whether something is a link by whether its a URL. 

As far as consistency goes, I'll note that docker desktop does it the same way Aspire currently does:

![DockerDesktopURLDisplay](https://github.com/dotnet/aspire/assets/9613109/80c96386-1b85-47c9-bca5-64ba499af988)

And Windows Terminal seems to do it like Aspire/Docker Desktop for auto-detected URLs:

![WindowsTerminalURLDisplay2](https://github.com/dotnet/aspire/assets/9613109/1add7cc1-fabf-4987-8e74-d91b59354428)

and somewhere in-between for non-URLs (dotted underline when not hovering):

![WindowsTerminalURLDisplay](https://github.com/dotnet/aspire/assets/9613109/eccabf57-28e0-4e20-9163-6de52631d13a)

Looks like that was an intentional decision in Windows Terminal (https://github.com/microsoft/terminal/issues/8123) though there's not a ton of discussion about it (OPs comments mostly mirror my thoughts though)

I understand these extra two examples are desktop apps not web pages, so there's a difference, but they're also displaying the same type of content, so not completely irrelevant.

Note also that I'm not saying we _shouldn't_ make this change (in fact I already prepared the PR to do so), just trying to put all the info out there, including my opinion.

@leslierichardson95

**Comment by leslierichardson95** [comment]
I'm good with either option but I think because Docker is always going to be relevant with Aspire, I'm leaning toward staying consistent with what docker does versus what AzDo or GitHub does. No worries if I get outvoted on that though.

**Comment by JamesNK** [comment]
Ok! I don't feel strongly about this. Can reopen if we change our mind.
