### ISSUE TITLE
Logging into sql from localhost

### ISSUE THREAD

**Issue by dotnetwizard** [dotnet/aspire#2855]
I'm trying to connect to SQL server from SSMS.

My setup looks like this
``` csharp
using Aspire.Hosting;

var builder = DistributedApplication.CreateBuilder(args);
// Service registration
var dbserver = builder
    .AddSqlServerContainer("sql", "P@ssw0rd", 1433)
    .AddDatabase("sqldata");

builder.AddProject<Projects.AwesomeProject>("ItsAwesome")
    .WithReference(dbserver);

builder.Build().Run();
```
The app sees the db just fine and now I would like to connect to the db from SSMS.

I see some information in the aspire dashboard
<img width="866" alt="image" src="https://github.com/dotnet/aspire/assets/48968515/cf699d6f-cacb-4971-885e-75ecbc445b08">

I have tried a few ways to log in with localhost:1433 or localhost,1433 and with the user being sa or
<img width="380" alt="image" src="https://github.com/dotnet/aspire/assets/48968515/c9e1c34f-8734-4f83-9166-e0ff57652608">

I noticed it has a different user in the containers "inspect" window on docker desktop
<img width="572" alt="image" src="https://github.com/dotnet/aspire/assets/48968515/205b67b9-d25f-44a6-9a11-04cac61d6898">

I tried that mssql user with no luck either. Any clues on what I'm doing wrong?

**Comment by davidfowl** [comment]
Try 127.0.0.1 instead of localhost.

**Comment by dotnetwizard** [comment]
That worked. Thanks

**Comment by dotnetwizard** [comment]
I will close this

**Comment by karolz-ms** [comment]
@dotnetwizard can you give us the full repro (e.g. GH public repo)? I would like to investigate why it does not work with `localhost`--it should 🤔

**Comment by davidfowl** [comment]
@karolz-ms we have this same problem with our SQL server resource:

https://github.com/dotnet/aspire/blob/36e40f89e15f1b049bd81c4bffbe7ec7b5a29ece/src/Aspire.Hosting.SqlServer/SqlServerServerResource.cs#L41

It uses 127.0.0.1 to connect to SQL server, localhost doesn't work. It's been this way to a while now. 

[IPv4Host gets translated to 127.0.0.01](https://github.com/dotnet/aspire/blob/36e40f89e15f1b049bd81c4bffbe7ec7b5a29ece/src/Aspire.Hosting/ApplicationModel/EndpointReference.cs#L163)

**Comment by dphsw** [comment]
> @dotnetwizard can you give us the full repro (e.g. GH public repo)? I would like to investigate why it does not work with `localhost`--it should 🤔

I've had the same problem, and the same fix has worked.  I've tried running the DatabaseContainers project from the Aspire samples repository and it happens there too, so unless it's something weird about certain systems you should be able to repro using that.  I tried logging on with sqlcmd from the command line and wasn't able to log on with that either, although running the same command inside the Docker container console worked.  I can't remember everything we tried before looking here - I recall we tried disabling the (non-containerizer) SQL Server service in case it was interfering with the connection to the containerized one, had tried connecting to different ports since Docker seemed to show a different port number than the Aspire dashboard (though the one shown by Aspire now works with the 127.0.0.1 fix above), checked that it did appear to be listening in netstat through dcpctrl, and the project was working on another devs computer (a possible difference being that they were using Rider whereas I'm using Visual Studio Preview 17.10.0).

**Comment by jdiederich** [comment]
In reference to the comment above about investigating why it does not work with localhost, possibly related to the Hack comment?
![image](https://github.com/dotnet/aspire/assets/5240745/cf3d242f-faec-4de9-998a-b40184bad6eb)
![image](https://github.com/dotnet/aspire/assets/5240745/62dfe1da-e6ee-42f3-b6e3-28f1fcfbf48f)

**Comment by davidfowl** [comment]
It is, and we still don't fully understand it. @karolz-ms This is likely a dcp proxy issues with ipv4/6 that is unresolved. We don't fully get why the SQL container acts differently here.

**Comment by karolz-ms** [comment]
I will take a look

**Comment by davidfowl** [comment]
Putting in 8.1

**Comment by davidfowl** [comment]
This isn't a dcp issue, it's a SQL server container issue https://stackoverflow.com/questions/47984603/using-sql-server-management-studio-to-remote-connect-to-docker-container.

**Comment by karolz-ms** [comment]
I verified that both `127.0.01,12345` and `[::1],12345` (the IPv6 loopback address) work when entered into SQL Server Management Studio (tried version 20.1, which was released just a few weeks ago). This was going through Aspire proxy (not directly to container host port), just like any part of Aspire application would. Also note that SQL Server wants a comma, not a colon, as a separator between the IP address and port.

For whatever reason `localhost` as a server name does not work with SSMS. I can only speculate that SSMS is trying to resolve `localhost` via network DNS, which won't work *by spec* (`localhost` is only resolvable locally), and so it fails to connect. That would be something for the SSMS developers to fix.

I am going to resolve this issue as "not planned" because it is external to Aspire.
