### ISSUE TITLE
Should log levels have translations?

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2878]
These are static and could have translations added:

![image](https://github.com/dotnet/aspire/assets/303201/eb864ca9-2136-47a6-82d0-04a08fd92694)

**Comment by adamint** [comment]
I believe we made a decision not to translate those?

**Comment by leslierichardson95** [comment]
I don't recall that conversation if we did have it at some point. What was the reasoning behind not localizing that dropdown?

**Comment by adamint** [comment]
@davidfowl

**Comment by leslierichardson95** [comment]
I'm currently checking what VS does in this scenario and I'm still a bit on the fence because the translation experience doesn't feel too consistent there either.  Here's the experience in the error window: 

![Image](https://github.com/dotnet/aspire/assets/7150306/18977ee2-0116-486d-8570-c78e666a617c)

In contrast, here's the experience in the Output Window:

![Image](https://github.com/dotnet/aspire/assets/7150306/b9557aa4-0e2e-4cd2-9097-b2acc4fea9dd)

Personally, I would lean towards following the latter image experience with the dropdown since that feels the most similar to this scenario.

**Comment by leslierichardson95** [comment]
For now, let's keep the log levels as-is instead of translating them, based off the similar enum value behavior in VS.
