### ISSUE TITLE
Dashboard OTLP auth follow up work

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#2995]
* ~OTLP API should support primary and secondary keys. Help make rotation possible.~
* Cert auth currently allows any valid cert. Should provide some way to limit client cert. @drewnoakes I think the resource service will do something similar. Is cert auth being added locally, or is the work just in the dashboard to provide a client cert for cloud hosting?

**Comment by drewnoakes** [comment]
> Should provide some way to limit client cert

I'm thinking each end can optionally be configured with the other end's cert, so that the thumbprints of each can be compared for equality and the connection rejected if they differ. That would allow simple cert validation, or a more rigorous approach.

We can likely share code between the OTLP and Resource Service auth bits here.

**Comment by eerhardt** [comment]
@JamesNK @drewnoakes - this is currently marked as "Low" priority, but it is impacting security. Is this an accurate priority rating? Or should this be bumped to "High" - meaning we won't ship 8.2 without it?

**Comment by JamesNK** [comment]
I moved it to high. Either way, the question doesn't matter anymore as [a PR was created yesterday](https://github.com/dotnet/aspire/pull/5172). It will be done for 8.2.
