### ISSUE TITLE
Auto-select resource when there is only one

### ISSUE THREAD

**Issue by martincostello** [dotnet/aspire#3072]
If you're using Aspire exclusively for use of the dashboard for local debugging, you can get the following experience where there's only one resource and you have to select it to see things when using the dashboard:

![image](https://github.com/dotnet/aspire/assets/1439341/128005db-8a56-4794-b375-b9c1f9a72710)

In the case where there's only one resource available, it would be a nice UX improvement if the dashboard automatically selected the only item in this scenario.

Happy to have a go at implementing it myself, but figured I'd open an issue about it first incase there's a reason it doesn't already do this.

**Comment by tlmii** [comment]
@martincostello Thanks for filing this issue. I agree that it would be nice, but unfortunately I think it is a little trickier than it sounds. 

There are no timing or ordering guarantees for how the resources become available to the pages. Because of that, when the console logs page loads, there might only be one resource, but another resource might "appear" a second or two (or even a minute or two) later. And when you launch the dashboard the next time they might act similarly, but in the reverse order. So the user could be presented with what is effectively a random selection choice. 

We could perhaps come up with some heuristic (e.g. track when the first resource is found and if it is X seconds after that, assume no more are coming and go ahead and select). But determining the correct heuristic and the right way to track it seems a bit out of scope at the moment. The deterministic state we have now seems an ok place for the moment at least. 

Happy to discuss further ideas though.

**Comment by martincostello** [comment]
That sounds fair, thanks for the explanation.

I figured there might be a reason it hadn't been implemented the "obvious" way originally, which is why I logged the issue first rather than plough straight into trying to make it do that with a PR straight away.

If you think this is too edge-case/difficult to do properly I'm happy for you to close it, otherwise I'll take a look at trying to come up with something at some point unless someone else picks it up first.
