### ISSUE TITLE
Add more test coverage for the WithDataVolume and WithDataBindMount resource extension methods

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#3185]
The `WithDataVolume` and `WithDataBindMount` resource extension methods added recently could do with more test coverage.

**Comment by joperezr** [comment]
This one is dependent on https://github.com/dotnet/aspire/pull/4468. A big part of the work here is adding cleanup so volumes are cleaned up after test runs.

**Comment by eerhardt** [comment]
I'm going to close this out as "completed". The only integration package that doesn't have these tests is Aspire.Hosting.Oracle, which is coming in https://github.com/dotnet/aspire/pull/4943. And half of them are disabled anyway because it doesn't work today. See https://github.com/dotnet/aspire/issues/5191.
