### ISSUE TITLE
Github codespaces - Dashboard resource urls has incorrect urls not specifying the github code space prefix or port forwarded ports

### ISSUE THREAD

**Issue by kvenkatrajan** [dotnet/aspire#3441]
The dashbaord launched from github codespaces displays the urls as it would locally without the github codespace prefix.

![image](https://github.com/dotnet/aspire/assets/102772054/057d6c73-d447-44ed-9968-e9b19f79e095)

Clicking on this would result in 404/invalid url

Modify the url to include the prefix For example of github code space prefix : https://turbo-space-tribble-xv6w5xxj76h6g64.github.dev/
. And here is an example of a port forwarded version of url is : https://turbo-space-tribble-xv6w5xxj76h6g64-5169.app.github.dev/counter

**Comment by davidfowl** [comment]
I'll take this one.

**Comment by davidfowl** [comment]
Moving to @tmeschter sounds good. I think we just need to know how to map the dev tunnels back to resources. 

cc @karolz-ms for his thoughts.

**Comment by mitchdenny** [comment]
I see tunnels as being layered on top of the base networking implementation we have today. So certain endpoints will also have a tunnel address. You wouldn't want services that are dependent on containers to have to route through the tunnel in normal circumstances.

For mobile scenarios I also think it would be great if you could bring up a link and show it as a QR code so you can hold you phone up to it and get pre-authenticated access into the tunnel.

**Comment by karolz-ms** [comment]
I assume in this case everything runs inside the codespace and all network traffic initiated by the application stays within the codespace local network. It is just that certain URLs (dashboard, frontend app and the like) are tunnelled to the dev host so that they can interact with them.

If my understanding is correct, I would think the dashboard should be made "tunnel-aware". When the dashboard is launched, there is an invocation parameter/environment variable that tells the dashboard the following: when you display an URL that the user should be able to CLICK (i.e. open with their browser), replace the (local host+port) part of the URL with the (tunnel host+tunnelled port). This also requires access to the "tunelled port configuration", which has to be passed to the dashboard or somehow retrieved by the dashboard from within the codespace. I am sure there is prior art for that already.

**Comment by davidfowl** [comment]
The dashboard shouldn't be doing this mapping, it should be the apphost.

**Comment by WardenGnaw** [comment]
> would full mapping data be available when the dashboard is launched? Or would ports be allocated over time as resources come online?

Are all the endpoints available for each project in the environment variables?

If I can somehow know that the app is going to launch with `http://localhost:1234`, I can query the VS Code API to get the Codespaces URL and set that as a new environment variable for the AppHost to use. 

If not, we could potentially use the [create Session Request](https://github.com/dotnet/aspire/blob/main/docs/specs/IDE-execution.md#create-session-request) where it will create a new run session and in the response there can be an updated URL for http/https.

**Comment by karolz-ms** [comment]
In general case the endpoint information may not be available until sometime after the application is launched (because the ports may be auto-allocated).

I did some more reading and this is one way we could make things work:

1. When the application starts, app host and DCP recognize they are running in Codespace environment based on presence of default environment variables https://docs.github.com/en/codespaces/developing-in-a-codespace/default-environment-variables-for-your-codespace
2. Every endpoint that the application is used is automatically mapped (by app host runtime or DCP) via the dev tunnel associated with the Codespace. https://docs.github.com/en/codespaces/developing-in-a-codespace/forwarding-ports-in-your-codespace By default private mappings are used, but we might want to have app host APIs that grant access to some ports to the organization, or even publicly (😬).
3. The mapped endpoints are annotated so that the dashboard resource service and the dashboard can differentiate them from "local" endpoints (usable only from within the Codespace).
4. The dashboard is told by the dashboard resource service that it is supposed to make HTML links out of "mapped" endpoints only. Other endpoints are displayed as text, like non-HTTP endpoints are displayed today.

The above might need some tweaking of app host, DCP, and dashboard service interaction, depending on what component does the port mapping and how these mapped endpoints show up in the app host model and the DCP model.

**Comment by mitchdenny** [comment]
Moving to backlog. We should decide whether this makes the cut for 9.0.

**Comment by mitchdenny** [comment]
Unassigning until it bubbles to the top of the stack as per our current practice :)

**Comment by mitchdenny** [comment]
Not sure why this got closed...

**Comment by mitchdenny** [comment]
Closing, I made some progress on this but tracking what I did over on this issue: #1178
