### ISSUE TITLE
Turn Kestrel configuration for project resources into endpoints

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#3456]
### Discussed in https://github.com/dotnet/aspire/discussions/3319

<div type='discussions-op-text'>

<sup>Originally posted by **fergalmoran** April  1, 2024</sup>
I have this in my launchsettings.json for my ApiService and it starts up fine (and serves the correct cert) when I run my project from the AppHost folder.

```  
"Kestrel": {
    "Endpoints": {
      "HttpsFromPem": {
        "Certificate": {
          "Path": "/etc/letsencrypt/live/<mylocaldomain>/cert.pem",
          "KeyPath": "/etc/letsencrypt/live/<mylocaldomain>/privkey.pem"
        },
        "Protocols": "Http1AndHttp2AndHttp3",
        "Url": "https://<mylocaldomain>:5001"
      }
    }
  }
```

However - the Endpoints column isn't populated properly in the dashboard?
![image](https://github.com/dotnet/aspire/assets/309139/215eb540-9d23-4119-9923-f2c67a50b004)

What am I missing?
</div>

**Comment by davidfowl** [comment]
To anyone that wants to start looking at this, [this method](https://github.com/dotnet/aspire/blob/ff7a691f7efb1f10d1cbddfd45b9e66894337f80/src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs#L88) takes the project information from the launch profile and turns it into endpoints and environment variables. 

We could also detect appsettings here and create endpoints. Here's an example of where we read kestrel configuration for http/2 settings https://github.com/dotnet/aspire/blob/ff7a691f7efb1f10d1cbddfd45b9e66894337f80/src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs#L268. This could be extended to find the endpoints etc.

A couple of things to figure out:
1. How do we name these endpoints? 
2. Does it override the launch profile (it does at runtime, so we should model this)
3. We should disable auto injection of ASPNETCORE_URLS for these endpoints (related to https://github.com/dotnet/aspire/issues/2241)

**Comment by SenKVarghese** [comment]
Hi,
I would like to take it up. Please note that this is my first open source contribution ever. Let me know what you think

**Comment by davidfowl** [comment]
Sure! We're here to help!

**Comment by davidebbo** [comment]
So here is how I understand things to work in a regular Web API with no aspirations (😝) :
- If it has no Kestrel config endpoints, the profile `applicationUrl` becomes an `ASPNETCORE_URLS` env variable, which Kestrel uses to define the endpoints.
- If it has Kestrel config endpoints, the profile is ignored, and instead `ASPNETCORE_URLS` takes the value from the Kestrel config endpoints.

e.g. if I have:

```json
  "Kestrel": {
    "Endpoints": {
      "Foo": { "Url": "http://*:5002" },
      "Bar": { "Url": "http://*:5003" }
    }
  }
```

I get `ASPNETCORE_URLS=http://*:5002;http://*:5003`.

Now in an Aspire app, things are a bit different:
- The host comes up with some random ports that it passes to the Web API (via `ASPNETCORE_URLS`).
- It instead uses the profile `applicationUrl` for the reverse proxy, which then forwards traffic to the generated ports. It does this to support multiple replicas.
- But if the app has Kestrel config endpoints, they completely take over and become what Kestrel listens on. But the proxy doesn't know that, and forwards to the generated ports, which no one is listening on. So it's all busted. Although if you go directly to the endpoint defined in Kestrel config, it works fine (bypassing the reverse proxy).

The question I have here is: when there are Kestrel config endpoints, is there a way to override them when the Aspire host runs the app? If not, then I don't see how the reverse proxy is going to work. And the best we can do is recognize the situation, turn off the reverse proxy, and directly show the Kestrel config endpoint in the dashboard. And obviously, we can't support multiple replicas. So that doesn't seem like a great story.

@davidfowl am I generally correct in how things work? All this is still new to me, so I want to make sure I get all this right before considering a code change.

**Comment by davidfowl** [comment]
> If it has Kestrel config endpoints, the profile is ignored, and instead ASPNETCORE_URLS takes the value from the Kestrel config endpoints.

I would say that the ASPNETCORE_URLS are ignored completely when Kestrel's configuration exists.

> The question I have here is: when there are Kestrel config endpoints, is there a way to override them when the Aspire host runs the app? If not, then I don't see how the reverse proxy is going to work. And the best we can do is recognize the situation, turn off the reverse proxy, and directly show the Kestrel config endpoint in the dashboard. And obviously, we can't support multiple replicas. So that doesn't seem like a great story.

This is the right insight. We can't change how kestrel will bind to so we need to disable the proxy in that case.

**Comment by davidebbo** [comment]
> I would say that the ASPNETCORE_URLS are ignored completely when Kestrel's configuration exists

To be precise, the `ASPNETCORE_URLS` passed in the process launch env is ignored. But internally, it still ends up setting that env variable based on the Kestrel config (I see this in Proc Exp). Anyway, that is more of a curiosity.

> We can't change how kestrel will bind to so we need to disable the proxy in that case.

Looking a bit deeper, I think we *can* change how it binds by setting an App Setting override env variable. e.g. in with the test config I have above, if you set `Kestrel__Endpoints__Foo__Url=http://*:5004` when launching the process, it overrides the Foo URL set in the Kestrel config. So I think in theory, it is possible to enable the proxy, but it adds complexity because it takes a different override mechanism.

Still, maybe it's best to start without proxy support as a first step.

**Comment by davidebbo** [comment]
As it stands, because of #4212, it seems that we cannot name these Kestrel endpoint anything other than http/https. And that matches what happens with the profile `applicationUrl` (which doesn't have a concept of names), so maybe it's not a terrible thing?
