### ISSUE TITLE
[WebToolsE2E][Aspire] After installing .NET 9 SDK and Aspire 9.0 P4 and sticking to use SDK 8.0 via environment variables, the browser fails to launch and the localhost refused to connect when running an 8.0 Aspire application.

### ISSUE THREAD

**Issue by v-elenafeng** [dotnet/aspire#3480]
**REGRESSION INFO** 

Doesn't repro with the Aspire 9.0 P3 Build last week.

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU

1. Install VS 17.10 Preview 3 FB

   - Web Workload
   - Includes Aspire 8.0.0-preview.5.24201.12
   - Includes SDK 8.0.300-preview.24203.14 and runtime 8.0.2
   - Apply the "dotnet-tools" feed for Aspire 8.0 P5

1. Install SDK 9.0 Preview 3 FB
  
   - Apply feed for SDK 9.0 Preview 3
   
1. Install Aspire SDK 9.0 P4 workload (Now its brand is 9.0 P4)

    - From: installLatest90p1FromReleaseBranch.ps1
    - Apply the "dotnet9" feed for Aspire 9.0 P4

1. You will run into issue [2186](https://github.com/dotnet/aspire/issues/2186), apply the workaround mentioned [here](https://github.com/dotnet/aspire/issues/2186#issuecomment-1967502080): SET VS_TEMPLATELOCATOR_SDKVERSION=version

**REPRO STEPS**

1. New Project > .NET Aspire Application > .NET 8.0

1. Build the solution and run it

**ACTUAL**
Unable to bring up the browser

![image](https://github.com/dotnet/aspire/assets/78580199/db6428b4-93c2-466c-b6b3-42e1e339649e)

Click "https: //localhost :17108" on the command window, the localhost refused to connect.

![image](https://github.com/dotnet/aspire/assets/78580199/3e107edb-0ce4-4114-87c5-04dc3d298653)

Note: 
- Doesn't repro with 8.0 Aspire Apps without installing SDK 9.0.

**EXPECTED**
The browser launches and the website displays correctly.

![image](https://github.com/dotnet/aspire/assets/78580199/d54d58bf-146c-4f52-86cf-14a2b1ad0577)

**Comment by joperezr** [comment]
Looks like there may be a misunderstanding here. What the environment variable `VS_TEMPLATELOCATOR_SDKVERSION` does is only taking effect for the VS template locator, but when running the app, the SDK used will still be 9.0 I believe. In order to force the use of the 8.0 SDK (which is the one that supports 8.0 Aspire apps today) you'd also need to have a global.json that forces the use of the 8.0 SDK. @balachir  would you mind trying using a global.json to see if this fixes the issue?

For what it is worth, this is just a point-in-time thing, as very soon we will add support for 8.0 aspire apps in the 9.0 workload, so once that happens this issue will no longer repro.

**Comment by v-yuwzh** [comment]
Hi Joperezr,
When add a global.json that forces use of the 8.0 SDK as below, this issue not repro.
![image](https://github.com/dotnet/aspire/assets/41678874/a4753054-559c-4f61-b3e0-d79093446dbc)

**Comment by joperezr** [comment]
Closing as this is no longer an issue.
