### ISSUE TITLE
[WebToolsE2E][Aspire] On a machine with only aspire 8.0 P6 installed, the dashboard token authentication will not pop up even if the aspire project is run for the first time.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#3651]
**REGRESSION INFO:** This is a new feature on Aspire 8.0 P6

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install the latest released sdk 8.0.204
3. Install Aspire 8.0 P6 [8.0.0-preview.6.24211.5]
4. Apply dotnet-tools Feed

**REPRO STEPS**

1. Open CMD, creating an Aspire Starter App using following commands:
    ```
    dotnet new aspire-starter -o aspire1
    cd aspire1\aspire1.AppHost
    dotnet run    ```

2. Manually go to url https://localhost:xxxx/login?t=xxxxxxx, the dashboard token authentication does not pop up

    - ![image](https://github.com/dotnet/aspire/assets/71361488/3cb88793-f6e2-48cb-8ab3-eabb8cdd6b44)

**ACTUAL**

On a machine with only aspire 8.0 P6 installed, the token authentication does not pop up even when running the aspire project for the first time.

**EXPECTED**

Token authentication can pop up when running the aspire project for the first time
![image](https://github.com/dotnet/aspire/assets/71361488/19dc56c1-5312-46e3-8684-983bd58019f1)

**Comment by balachir** [comment]
@v-sherryfan I believe this is By Design. When you click the full URL shown in the console (i.e. the URL is of the form https://localhost:xxxx/login?t=xxxxxxx), you are passing the token as a query string parameter. It'll use this token and create a localhost cookie, and then automatically log you in to the dashboard. So, it doesn't show you the screen prompting you to manually enter the token. cc: @JamesNK 

FYI, this is the reason why in step 5 of issue [#3613](https://github.com/dotnet/aspire/issues/3613), I try to manually type the URL without the token in the query string.

**Comment by JamesNK** [comment]
This is by design.
