### ISSUE TITLE
Starter template with name `starter xyz.foo-bar` generates a broken Test project

### ISSUE THREAD

**Issue by radical** [dotnet/aspire#4025]
1. `dotnet new aspire-starter -t mstest -o "starter xyz.foo-bar"`
2.  `dotnet run` for `AppHost` works fine
3. `dotnet test` for the `Tests` projects fails to build:

`/private/tmp/test/starter xyz.foo-bar/starter xyz.foo-bar.Tests/WebTests.cs(12,87): error CS0234: The type or namespace name 'starter_xyz' does not exist in the namespace 'Projects' (are you missing an assembly reference?) [/private/tmp/test/starter xyz.foo-bar/starter xyz.foo-bar.Tests/starter xyz.foo-bar.Tests.csproj]`

`WebTests.cs` line 12: `var appHost = await DistributedApplicationTestingBuilder.CreateAsync<Projects.starter_xyz.foo_bar_AppHost>();`

Generated class name in `obj/Debug/net8.0/Aspire/references/_AppHost.ProjectMetadata.g.cs`:
`public class starter_xyz_foo_bar_Tests`

The generated class name does not seem to follow the same rules as the template name generation.

cc @timheuer @DamianEdwards @joperezr

**Comment by timheuer** [comment]
yeah okay, clearly we need someone from template engine to help explain how we are doing something wrong here.

**Comment by joeloff** [comment]
Is this for .NET 8?

**Comment by radical** [comment]
And https://github.com/dotnet/aspire/issues/4024 is a related issue, which seems to complicate things. Maybe we need to "save" the namespace somewhere at the project generation time, and use that when generating this class at build time. That way we don't have to try to emulate what the template engine does.

**Comment by radical** [comment]
A better way might be to essentially generate the name like `starter_xyz_foo_bar_AppHost` as our targets do. But in the generated `.cs` files where we currently have:
`var apiService = builder.AddProject<Projects.AspireStarterApplication__1_ApiService>("apiservice");`

.. replace `.` with `_` for the `AspireStarterApplication__1` namespace. Does the template engine support generating a string by doing a replace on `AspireStarterApplication__1` which gives the namespace?

**Comment by radical** [comment]
https://github.com/dotnet/templating/wiki/Available-Symbols-Generators#regex might be needed.

**Comment by joeloff** [comment]
Something else worth looking at might be to see what happens when you pass in unicode glyphs. C# only supports letter (Lu, Ll, Lt, Lm, Lo or Nl) , digit (Nd), connecting (Pc), combining (Mn or Mc) and formatting (Cf) categories and the engine usually replace invalid characters with underscores. If you're doing your own replacement for the generated code, something like GB18030 might get tripped up.

This is a sample string that was used in a test a while back: "龦唉丂荳◎℉㐁&ᠭᠤ སྲིད خەل ꌠ ᥕ᧞"

**Comment by DamianEdwards** [comment]
OK I might have made a breakthrough on this one. I've changed the starter app to use a `sourceName` of `Aspire-StarterApplication` instead of `AspireStarterApplication.1` or `Aspire.StarterApplication1`, etc., to match what the Blazor template does and now it seems to be working. I'll send a PR and we can further scrutinize there.
