### ISSUE TITLE
[WebToolsE2E][Aspire] Install VS 17.10 GA (PR 546661) and Web+Multi+Nodejs workload, and then install Aspire 8.0 P7 from ps1 script failed: Version 34.0.95 of package microsoft.android.sdk.windows.msi.x64 is not found.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#4104]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 GA VSE 
    - from PR 546661, buildId=9513227, release channel
    - Web workload + .NET Multi-platform App UI development + Nodejs workload
    - Include sdk 8.0.300 and runtime 8.0.5
    - Includes Aspire 8.0.0-preview.6.24214.1
3. Install Aspire 8.0 P7 from PS1 script

**ACTUAL**
Workload update failed: One or more errors occurred. (Version 34.0.95 of package microsoft.android.sdk.windows.msi.x64 is not found in NuGet feeds xxx)
![image](https://github.com/dotnet/aspire/assets/71361488/582cd385-87d0-436f-80df-92e5501a642c)

**NOTE:**

- Not repro on VS 17.10 GA VSE + Web workload + Aspire 8.0 P7 from PS1 script

**EXPECTED**
After installing VS 17.10 GA and Web+Multi+Nodejs workload, and then successfully installing 8.0 P7 from ps1 script.

**Comment by joperezr** [comment]
This issue isn't really about aspire. The Install script will mainly do two things, update all of the workload manifests installed, plus install aspire using the version passed in on the rollback file. The issue you are hitting is because on that first step of updating the workload manifests, your SDK had knowledge of a newer workload that was available (in Nuget.org) https://www.nuget.org/packages/Microsoft.Android.Sdk.Windows.Msi.x64/34.0.95 and so it was trying to install that updated manifest. The problem is that the script forces the use of a single feed (the dotnet-tools feed) which makes it so that the package 34.0.95 isn't found, and so you get the above error. The workaround is to ensure that before running the script, you have updated your workloads by running `dotnet workload update` which would use NuGet.org to pull all the latest manifests.

**Comment by joperezr** [comment]
I'm closing this as it isn't really actionable from our side, but please let me know if the above doesn't fix your situation and I'm happy to help further.

**Comment by v-sherryfan** [comment]
@joperezr Thanks for detailed information. I try to run `dotnet workload update` but I get another error.
![image](https://github.com/dotnet/aspire/assets/71361488/c83e6208-88be-430f-a9d2-932cddaa0194)

**Comment by joperezr** [comment]
Looks like you are using an unreleased version of the SDK, which carries dependencies to workloads and packs that aren't released yet. The one you display above is only available in an internal build feed. This is a known drawback when working with pre-released SDKs which depend on prerelease workloads

**Comment by v-sherryfan** [comment]
Verified this issue is not reproduced on VS 17.10 GA (Include Aspire 8.0.0 and SDK 8.0.300). 
Also this issue has nothing to do with aspire, you only need to apply multi feeds to pass.
