### ISSUE TITLE
Dcp can't seem to proxy Django applications

### ISSUE THREAD

**Issue by wmeints** [dotnet/aspire#4158]
I am trying to add support for Django and I'm running into this weird problem where Django doesn't seem to like cooperate with Dcp. But I'm unsure if the problem lies with Dcp or with Django.

The problem I see is that the app is running succesfully, but when I open the link in the dashboard I never receive a response from the Django Server. It looks like the server never receives a request from Dcp. I tried accessing the Django app without the proxy and that works okay.

I made a short video to demonstrate what happens:

https://youtu.be/Ih6gjU_uewI?si=VeSfc6FmcL5u5Z9y

For a full repro, please check out the sample on my github repo: https://github.com/wmeints/aspire-django-demo

**Comment by davidfowl** [comment]
@karolz-ms can you take a look?

**Comment by karolz-ms** [comment]
Will do. Thanks for the report and a repro, much appreciated @wmeints

**Comment by karolz-ms** [comment]
OK so there is a couple of problems with this scenario: one is an Aspire problem, and one is the application problem.

The Aspire problem is that the `TargetPort` setting on the endpoint is not honored when the endpoint is proxied. Instead, Aspire ignores this setting and runs the application on a random port. That issue has been fixed in the Aspire main branch via https://github.com/dotnet/aspire/pull/3611, but unfortunately that change did not make it to `release/8.0` branch and will probably only arrive in 8.1 release.

The second problem is that the application is not honoring the `DJANGO_HTTP_PORT` environment variable and instead always listens on port 8000. Python/Django is not my strong suit, but I managed to make the app work by adding a custom `runserver_env` Django command following [the docs](https://docs.djangoproject.com/en/5.0/howto/custom-management-commands/):

```python
from django.core.management.commands.runserver import Command as Runserver
import os

class Command(Runserver):
    def handle(self, *args, **options):
        options['addrport'] = os.getenv('DJANGO_HTTP_PORT', '8000')
        return super().handle(*args, **options)
```

After changing the AppHost project to use the custom `runserver_env` command instead of `runserver` command the program works. Not sure if this is a good solution for production (probably isn't) but the point is, the app should listen on the port specified by the `DJANGO_HTTP_PORT` environment variable, if present.

@wmeints let me know please if this is enough information to get this issue closed as fixed, with the caveat that the fix may need some time to be released publicly.

**Comment by wmeints** [comment]
Well, that explains a lot :-) Thanks for looking into this! I can work around the limitation for now. I'm happy to close this issue.
