### ISSUE TITLE
Limits are not per-resource despite documentation

### ISSUE THREAD

**Issue by AntonZhuchkovXOR** [dotnet/aspire#4173]
**Affected Image:** `mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.7`

**Issue:**
We're encountering an unexpected behavior where despite the documentation indicating that limits are applied per-resource, we're observing that other resources are getting wiped of their logs and traces. Specifically, one of our resources is casting a batch of events every 3 seconds, and only this resource remains visible in the dashboard while others seem to be cleared.

**Expected Behavior:**
According to the documentation, limits should be enforced per-resource, ensuring that all resources have equal visibility on the dashboard regardless of their activity levels.

**Steps to Reproduce:**
1. Deploy multiple resources using the specified image.
2. One resource should cast a batch of events every 3 seconds.
3. Monitor the dashboard for log and trace visibility.

**Additional Information:**
This behavior is hindering our ability to accurately monitor and debug our resources. We believe this discrepancy between the expected behavior and the observed behavior constitutes a bug and should be addressed.

We appreciate any assistance or insight into resolving this issue. Thank you.

**Comment by davidfowl** [comment]
@samsp-msft  @JamesNK This seems important to understand.

**Comment by samsp-msft** [comment]
Logs should be per-resource as they are a distinctly per resource concept.
Traces gets more complicated as they aggregate data from multiple resources. Although a trace is made up of individual spans that are tagged from their resources, we store them based on the traceid so that all related spans are collected together as part of the trace. 
This would mean either storing the data on a per-span basis and re-collating constantly to build the list of traces or trying to figure out which traces hold spans from which resource, and to recycle smarter.

How long is it before the trace data is being recycled from the buffer?

**Comment by samsp-msft** [comment]
We should update the docs for 8.1.

**Comment by AntonZhuchkovXOR** [comment]
> How long is it before the trace data is being recycled from the buffer?

In our case — less than a minute.
