### ISSUE TITLE
Error in Aspire run session could not be started: failed to connect to IDE run session notification endpoint: unexpected EOF

### ISSUE THREAD

**Issue by GoranDeveloper** [dotnet/aspire#4437]
Microsoft Visual Studio Community 2022 (2) (64-bit) - Preview
Version 17.11.0 Preview 1.1
9.0.100-preview.4.24267.66 

fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
      failed to start Executable        {"Executable": {"name":"apiservice-0faj1o0"}, "Reconciliation": 6, "error": "run session could not be started: failed to connect to IDE run session notification endpoint: unexpected EOF"}

Can someone assist ? 
I go in production with aspire.

Thank you

**Comment by davidfowl** [comment]
@joperezr Can we fix the .NET 9 situation with the workloads? Maybe we need to document something that we can point people at.

**Comment by joperezr** [comment]
Yeah, the fix is to change the 9.0 SDK to use Aspire 8.0 instead of it pulling down a dead end 9.0 version. After that we can also likely de-list 9.0 workload packages.

I'll take care of it this week. We'll still have the issue with requiring the 8.0 runtime for the dashboard, but we can fix that too.

**Comment by joperezr** [comment]
I've put up PR https://github.com/dotnet/sdk/pull/41562 which will make it so that even 9.0 SDKs use 8.0 Aspire, and will enable us to delist 9.0 preview packages to avoid future confusions, and also to simplify the fix to issues like this by just requiring an SDK update to fix them.

@GoranDeveloper I noticed that I didn't actually help you fix the current issue. Can you please try using Aspire 8.0 instead of the 9.0 version? For  now and until the PR I mention above is merged, you can do this by following these steps:

1. Generate a file called rollback.txt with the following contents:
```json
{
  "microsoft.net.sdk.aspire": "8.0.1/8.0.100"
}
```
2. From the command line, run `dotnet workload update --skip-sign-check --from-rollback-file ./rollback.txt`
3. Then, also run:  `dotnet workload install aspire --skip-sign-check --from-rollback-file ./rollback.txt`
4. Finally, go to your Aspire solution, and update all references to Aspire packages to use version 8.0.1 instead. This includes the reference to `Aspire.Hosting.AppHost` in your AppHost project.

Let me know if the above doesn't work, or if it doesn't fix the issue you are hitting.

**Comment by GoranDeveloper** [comment]
@joperezr @davidfowl 
Hi, it seem to work.
Thank you both for you help and support.

**Comment by joperezr** [comment]
Happy to help. Please let us know if you hit any other issues 😃

**Comment by Hantse** [comment]
Hello,

I'm quite surprise, i've the same issue, it's normal publish version with major issue ?

**Comment by davidfowl** [comment]
.NET 9 is a preview, .NET Aspire targets .NET 8, not 9.

**Comment by Hantse** [comment]
But if we stay on version 8.0, it's not possible to host/test others project type in 9.0 version i'm right ?
