### ISSUE TITLE
Add ResourceNotificationService.WaitForResourceAsync

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#4445]
## Background and Motivation

When writing tests with `Aspire.Hosting.Testing` against AppHost projects, it's beneficial to have a programmatic way to wait on a resource to transition to a known state from within a test, so that tests don't needlessly attempt to connect to a resource when it's known to be in a state where that attempt will fail, e.g. before it transitions to the "Running" state as shown in the dashboard, or reported by `ResourceNotificationService`.

## Proposed API

We should consider adding a new method `Aspire.Hosting.ApplicationModel.ResourceNotificationService.WaitForResourceAsync` to aid in these scenarios, along with adding more common states to `Aspire.Hosting.ApplicationModel.KnownResourceStates`.

```diff
namespace Aspire.Hosting.ApplicationModel;

public class ResourceNotificationService
{
    public ResourceNotificationService(ILogger<ResourceNotificationService> logger);
+   public ResourceNotificationService(ILogger<ResourceNotificationService> logger, IHostApplicationLifetime hostApplicationLifetime);
+   public Task WaitForResourceAsync(string resourceName, string targetState = KnownResourceStates.Running, CancellationToken? cancellationToken = null);
+   public Task<string> WaitForResourceAsync(string resourceName, IEnumerable<string> targetStates, CancellationToken? cancellationToken = null);
}

public static class KnownResourceStates
{
    public static readonly string Hidden = "Hidden";
+   public static readonly string Starting = "Starting";
+   public static readonly string Running = "Running";
+   public static readonly string FailedToStart = "FailedToStart";
+   public static readonly string Stopping = "Stopping";
+   public static readonly string Exited = "Exited";
+   public static readonly string Finished = "Finished";
}
```

## Usage Examples

```csharp
[Fact]
public async Task GetWebResourceRootReturnsOkStatusCode()
{
    // Arrange
    var appHost = await DistributedApplicationTestingBuilder.CreateAsync<Projects.MyAspireApp_AppHost>();
    appHost.Services.ConfigureHttpClientDefaults(client =>
    {
        client.AddStandardResilienceHandler();
    });

    await using var app = await appHost.BuildAsync();
    var resourceNotification = app.Services.GetRequiredService<ResourceNotificationService>();
    await app.StartAsync();

    // Act
    await resourceNotification.WaitForResourceAsync("webfrontend", KnownResourceStates.Running);
    var httpClient = app.CreateHttpClient("webfrontend");
    var response = await httpClient.GetAsync("/");

    // Assert
    Assert.Equal(HttpStatusCode.OK, response.StatusCode);
}
```

## Alternative Designs

We initially thought about adding a new public type in `Aspire.Hosting.Testing` that could be resolved from DI manually and have the `WaitForResourceAsync` method on that but given the target state is aligned with the state text reported by `RequestNotificationService` it seems appropriate to add it directly there.

Perhaps `WaitForResourceAsync` could just be `WaitForAsync` given it's already on the `RequestNotificationService`.

## Risks

The resource states are just string values and aren't enforced anywhere, or even used to set states by `Aspire.Hosting`, as the states generally come from DCP. It seems reasonable that we should have a set of common known states though.

The overload `WaitForResource("myresource")` where the `targetState` parameter is defaulted could be something we'd prefer to map to a different behavior in the future, e.g. once health checks are added it could wait for health checks to be healthy before returning rather than just status update text matching.

**Comment by afscrome** [comment]
Did mean `ResourceNotificationService` in the issue title?

Funnily enough, I happened to implement a version of `WaitForResource(state)` yesterday in my AppHost project, so +1 for being in the core of aspire rather than being a test extension.  (Context of why I was doing this I was refactoring some of https://github.com/davidfowl/WaitForDependenciesAspire/ make it play better with non Executable / Container resources).

One problem I have found with that implementation is that it does wait forever if the resource terminates/fails before reaching the expected state.  (e.g. if you wait for `Running` but resource goes to `FailedToStart`).  This actually works quite nicely for my use case, but in tests, I'd imagine you want your tests to fail fast rather than wait for a default timeout).  Ideally not only would `WaitForResourceAsync` wait for the resource to reach the expected state, but it should also fail fast once the resource reaches a point where it can never get into the desired state.

That said, I have found the status changes APIs a bit awkward to use as a whole:

1. It's hard to know what the states are, and there are lots of different status that effectively meant he same thing.  (e.g. `Exited`, `Finished` and `FailedToStart` are really all different forms of terminating state).  Adding more well known status helps with part of this, but it doesn't help with non well known states
2. If waiting for a specific state, it's hard to know whether that state is still possible.  (e.g. if I'm waiting for a Healthy status, but the resource terminates, there's not much point continuing to wait for the Healthy state)
3. I've also not found the separate `Starting` vs `Started` states particularly helpful as you're not able to use them to block progression to the next state, so most of the time by the time you react to the starting events, the resource has transitioned to the started event  (This is probably a broader issue around Resource Lifecycles rather than `ResourceNotificationService`, but I'm mentioning it for completeness.)

The text status works really well for the purpose of displaying on a dashboard and human readability, but it seems like it could do with some additional more structured / strongly typed properties in the underlying API to provide for some machine readability of the state.  e.g. `Starting`, `Running`, `Terminated`.  With addition of health checks, potentially `Healthy` and `Degraded` (although perhaps resource health status should be separate.)  `WaitForResourceAsync` could then be built on top of that more strongly typed model which I think would help mitigate some of the risks identified

For completeness, the implementation I ended up with was (haven't solved the infinite waiting problem as that doesn't' matter in my use case,)

```cs
async Task WaitForState()
{
    logger.LogInformation("Waiting for {Resource} to be in state {States}", waitOn.Resource.Name, waitOn.States);
    await foreach (var resourceEvent in resourceNotificationService.WatchAsync(_cts.Token))
    {
        if (resourceEvent.Resource == waitOn.Resource
            && waitOn.States.Contains(resourceEvent.Snapshot.State?.Text))
        {
            logger.LogInformation("{Resource} is {State}", waitOn.Resource.Name, resourceEvent.Snapshot.State?.Text);
            return;
        }
    }
}
```

**Comment by wuhkuh** [comment]
Would this proposal also be a solution for our use-case? 

We have a Yarn monorepo containing multiple frontend apps, that cannot boot nonsequentially: dependency installation cannot be performed concurrently, as they will race to update the state in `node_modules`, leading to a broken state.

**Comment by afscrome** [comment]
@wuhkuh Take look at https://github.com/davidfowl/WaitForDependenciesAspire/ - that should cover what you're after.

**Comment by DamianEdwards** [comment]
@afscrome yes indeed, thanks!

To be clear, this isn't intended to be the full `WaitFor` experience that integrates with health checks, etc. that will enable controlling the order of resource startup during the dev inner loop. Integrating @davidfowl's WaitForDependencies example will take longer than we're planning for 8.1 and we wanted to improve the experience in test projects using `Aspire.Hosting.Testing`, so this design is simply about adding a higher-level API on `ResourceNotificationService` without introducing any new concepts or constructs. This includes introducing more semantics around resource states beyond the simple text states we have right now, as again that's a bigger work item. We think this is a reasonable building block to add for now that adds utility without introducing more complex concepts.

With this new method, a test can easily wait for one or more states to be reach with a `Task.WhenAny`, e.g.:

```csharp
[Fact]
public async Task GetWebResourceRootReturnsOkStatusCode()
{
    // Arrange
    var appHost = await DistributedApplicationTestingBuilder.CreateAsync<Projects.MyAspireApp_AppHost>();
    appHost.Services.ConfigureHttpClientDefaults(client =>
    {
        client.AddStandardResilienceHandler();
    });

    await using var app = await appHost.BuildAsync();
    var resourceNotification = app.Services.GetRequiredService<ResourceNotificationService>();
    await app.StartAsync();

    // Act
    await Task.WhenAny(
        await resourceNotification.WaitForResourceAsync("webfrontend", KnownResourceStates.Running),
        await resourceNotification.WaitForResourceAsync("webfrontend", KnownResourceStates.FailedToStart)
    );
    var httpClient = app.CreateHttpClient("webfrontend");
    var response = await httpClient.GetAsync("/");

    // Assert
    Assert.Equal(HttpStatusCode.OK, response.StatusCode);
}
``` 

That said, it makes we wonder if we shouldn't add an overload that accepts an `IEnumerable<string>` of states to wait on to make this even more ergonomic (and efficient), e.g.:

```csharp
public Task WaitForResourceAsync(string resourceName, IEnumerable<string> targetStates, CancellationToken? cancellationToken = null)
```

**Comment by afscrome** [comment]
For the return type of `WaitForResourceAsync`, do you think it's worth returning the whole snapshot rather than just the text of the matching state?  In particular, I'm thinking about waiting on completion / termination as you may well want to differentiate between completed successfully and completing unsuccessfully.  (e.g. by checking the Exit Code).

Alternatively, maybe it would make sense to add a `WaitForCompletion` / `WaitForSuccessfulCompletion` method that handles this.
