### ISSUE TITLE
`docker build` and `docker pull` logs in dashboard are out of order

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#4635]
Given the following code (8.1). Open the `withdockerfile` playground project and launch it. Notice in the dashboard that the logs from docker build/docker pull that are prepended to the output are out of order:

![image](https://github.com/dotnet/aspire/assets/513398/ce286a1f-d233-41f1-a0c1-017139822647)

Once this bug is fixed we can close #4535 as well.

**Comment by mitchdenny** [comment]
As part of this work it would be good to get a test that covers that the logs are being generated and that they are in the correct order (probably can't match on exact logs).

**Comment by danegsta** [comment]
Just checked the output from the Docker CLI for build and this looks to just be how the output is reported. I'm guessing buildx is doing some parallel layer building for performance:

```
#2 [internal] load metadata for docker.io/library/golang:1.16
#2 ...

#3 [internal] load metadata for mcr.microsoft.com/cbl-mariner/base/core:2.0
#3 DONE 0.3s

#2 [internal] load metadata for docker.io/library/golang:1.16
#2 DONE 2.3s

#4 [internal] load .dockerignore
#4 transferring context: 2B 0.0s done
#4 DONE 0.1s
```

**Comment by JamesNK** [comment]
So, not a bug in how Aspire dashboard is displaying logs?

**Comment by danegsta** [comment]
Unfortunately, this does look like a display bug after all; I just checked the raw logs from DCP vs the output in the dashboard and the startup logs are reversed for a given timestamp value.

![image](https://github.com/dotnet/aspire/assets/50252651/fcbec1ed-abe2-42fa-9f26-a1b55b54e15a)

**Comment by danegsta** [comment]
I think it's this check: https://github.com/dotnet/aspire/blob/de19f5f9861afcb0a5520803801d846632540724/src/Aspire.Dashboard/Components/Controls/LogViewer.razor.cs#L101

New timestamped log entries are always getting inserted after the previous log entry timestamp, even if there are multiple log entries with the same timestamp (so they end up sorted in reverse order, since the newer lines keep getting appended right after the previous timestamp.

Should just be able to reverse the check and look for a later timestamp value or fall through to append at the end of the feed if there isn't one.

**Comment by danegsta** [comment]
Or actually, just `<=` should work.

**Comment by JamesNK** [comment]
Ok. I always thought the logic added into the LogViewer to order lines was sus AF 😬

**Comment by mitchdenny** [comment]
![image](https://github.com/dotnet/aspire/assets/513398/4e7c6a5a-6714-4f32-bab4-62186793866a)
