### ISSUE TITLE
Refactor AspirePageContentLayout so that MainSection isn't recreated when the layout changes

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#4961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

AspirePageContentLayout recreates MainSection when the layout changes which means all browser state is lost.

I think we should be able to achieve the same effect with CSS. I think resizing the page can just change the class on the content layout div, and the content inside the div can react to it as needed. Server-side updates are fine for the other sections, but the main section should be persistent.

* Avoids having to capture and preserve the state of everything which can create its own bugs, see https://github.com/dotnet/aspire/issues/4954
* Also avoids the problem of losing browser only state such as scroll position, etc

### Expected Behavior

MainContent isn't recreated when resizing the browser.

**Comment by JamesNK** [comment]
@tlmii I think your CSS expertise would be good here.

**Comment by tlmii** [comment]
I spent a couple quick moments looking at it this morning. I think its doable, but I don't think I'll have the bandwidth before leave to really contribute to it. Off the top of my head, one way I might tackle it is:

- As a first step I'd look to see if the three parts of the if/else if/else block in AspirePageContentLayout.razor could potentially be consolidated into one (with the conditionals inside of it instead). The first and third parts are very similar in structure and the second is almost a pure subset of the other two. The first/third parts could probably be made even more similar with a little care (it'd take a lot of testing the changes in both modes, so its not a quick thing to do) which would make it easier to consolidate them.
- If you're able to do that, then you can start using media queries to potentially replace some of those (newly-inner) conditionals with some display:none or similar CSS changes to hide/move things. 

OR...

I don't know enough about the inner workings of blazor and how it chooses to re-create, but I wonder if just getting to one single instance of `@MainSection` on the page is sufficient to solve the problem here. Lots of other conditionals everywhere around it could be fine. If so, another thing you could do without going full CSS is try to break it down into before/after chunks. 

Something like this:

```
<div class="content-layout">
    @if (ViewportInformation.IsDesktop)
    {
        <div style="grid-area: page-header; @HeaderStyle">
            @if (AddNewlineOnToolbar)
            {
                @PageTitleSection

                <FluentToolbar Orientation="Orientation.Horizontal">
                    @ToolbarSection
                </FluentToolbar>
            }
            else
            {
                <FluentToolbar Class="title-toolbar-inline" Orientation="Orientation.Horizontal">
                    @PageTitleSection
                    @ToolbarSection
                </FluentToolbar>
            }
        </div>

    }
    else if (!IsSummaryDetailsViewOpen)
    {
        <div style="grid-area: page-header">
            <FluentToolbar Orientation="Orientation.Horizontal" Style="@HeaderStyle">
                @PageTitleSection

                @if (!AddNewlineOnToolbar)
                {
                    @MobilePageTitleToolbarSection
                }
            </FluentToolbar>

            @if (AddNewlineOnToolbar)
            {
                <div style="padding: calc(var(--design-unit) * 2.5px)">@MobilePageTitleToolbarSection</div>
            }
        </div>
    }

    @{
        var mainSectionStyle = ViewportInformation.IsDesktop ? $"grid-area: main; overflow: auto; {MainContentStyle}" : GetMobileMainStyle();
        // Just a single @MainSection now
    }
    <div style="@mainSectionStyle">
        @MainSection
    </div>

    @if (ViewportInformation.IsDesktop)
    {
        if (FooterSection is not null && ShouldShowFooter)
        {
            <div style="grid-area: footer">@FooterSection</div>
        }
    }
    else if (!IsSummaryDetailsViewOpen)
    {
        if ((FooterSection is not null && ShouldShowFooter) || ToolbarSection is not null)
        {
            <div style="grid-area: footer">
                @if (FooterSection is not null && ShouldShowFooter)
                {
                    @FooterSection
                }

                @if (ToolbarSection is not null)
                {
                    <FluentButton Class="mobile-toolbar"
                                  Appearance="@Appearance.Accent"
                                  OnClick="@OpenMobileToolbarAsync">
                        @(MobileToolbarButtonText ?? LayoutLoc[nameof(Layout.PageLayoutViewFilters)])
                    </FluentButton>
                }
            </div>
        }
    }
</div>
```

In my quick testing of the above, it didn't make any difference, at least on the scroll position issue. That makes me wonder if there might be something else going on here that's triggering the re-creation? I'd think blazor would just be re-using the results of that RenderFragment since it doesn't change... @SteveSandersonMS maybe you can tell me why I'm wrong there? 

Seems like if that part doesn't work, a pure CSS solution won't work either (since a pure CSS solution would just be this with a few less server-side conditionals, but no impact on the main section).

I must be missing something about what's causing the underlying issue.

cc @JamesNK @adamint

**Comment by adamint** [comment]
Completed in above pr
