### ISSUE TITLE
Make referencing Node/Npm projects consistent with python and dotnet

### ISSUE THREAD

**Issue by maddymontaquila** [dotnet/aspire#5020]
## Background and Motivation

When adding a Python or Dotnet project, the API is `builder.AddProject` / `builder.AddPythonProject` - Npm/Node should probably be consistent and not AddNodeApp etc. Also I'm sure there is a reason they are two separate APIs, but... feels like we should have builder.AddJSProject("node") or something and abstract that

## Proposed API

no

## Usage Examples

builder.AddNodeProject("pls");

**Comment by aaronpowell** [comment]
I find the naming a little confusing because the `NodeAppResource` and `PythonProjectResource` are of type `ExecutableResource` not `ProjectResource`, which means that from a manifest perspective they are treated differently (resulting in a different hosting model).

I would argue that it should be `AddPythonApp` to align with the current Node style and thus have a point of difference that they will be handled differently in the manifest for hosting.

**Comment by maddymontaquila** [comment]
after talking with @DamianEdwards I agree with you @aaronpowell !!! It should be "AddNodeApp" and "AddPythonApp" and we should reserve "Add<>Project" for things with a .csproj file!

**Comment by DamianEdwards** [comment]
We should add the new method (`AddPythonApp`) and obsolete the existing one in 8.2 and, remove the old one in 9.0
