### ISSUE TITLE
Change resources log column title to console

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#5384]
I think the UI would be less confusing if the title of the logs column was "Console". It would mean less confusion with structured logs, and it would be consistent with the sidebar UI which calls the page console already.

![image](https://github.com/user-attachments/assets/6aed6f8f-4bc4-49f3-9d90-e0584f4a521f)

**Comment by drewnoakes** [comment]
This interacts with #2148. Would you want to see "Console" in the cells too?

Also is it expected that this just says "Structured" and not "Structured logs":

![image](https://github.com/user-attachments/assets/6bf47d51-055e-4434-8d35-228f386a2040)

**Comment by JamesNK** [comment]
> Would you want to see "Console" in the cells too?

Yes

> Also is it expected that this just says "Structured" and not "Structured logs":

I think that was chosen for size and consistency (other titles are one word).

**Comment by drewnoakes** [comment]
> > Would you want to see "Console" in the cells too?
> 
> Yes. Although I think if "View" was going to be replaced, it should probably be an icon rather than another text button.

An icon is worth considering. @leslierichardson95 what do you think about using icons in the "Console Logs" and "Details" columns, instead of using the text "View" like we have today?

> Or even better, move the actions into a context menu like Windows Docker UI.

For people who use this navigation regularly, this might slow you down. However a menu would make it easier to add more items in there, like showing metrics/structured logs. cc @leslierichardson95 for input.

> > Also is it expected that this just says "Structured" and not "Structured logs":
> 
> I think that was chosen for size and consistency (other titles are one word).

Single words are great, but "Structured" doesn't make much sense as a standalone term. I think if I were seeing this UI for the first time, I'd find that confusing.

**Comment by JamesNK** [comment]
Not needed after action button refactor
