### ISSUE TITLE
Throw a friendly error from Aspire if Docker isn't running

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspire#5533]
This is what a user sees today if they run Aspire and docker isn't running.

![image](https://github.com/user-attachments/assets/45987dab-175d-4b78-b44a-b7a8a3b8850b)

Should display a nice, friendly error message. Something like, "Failed to connect to Docker. Ensure that Docker is running."

**Comment by JamesNK** [comment]
Is there a different error if Docker isn't installed? Should test that scenario and ensure there is a good error message.

**Comment by maddymontaquila** [comment]
For the lurkers, this is a huge lift to actually fix, so in the meantime we definitely need to make the error message palatable and actually informative. There is a diff error if docker isnt installed.

**Comment by maddymontaquila** [comment]
cc @leslierichardson95

**Comment by davidfowl** [comment]
Another idea would be to lean into the dashboard and show it there instead of stopping the application from starting. Container resources would fail and we with the new restart feature, maybe enable restarting the container.

**Comment by JamesNK** [comment]
There isn't an API for the host to tell the dashboard to show messages. But since we know if docker is healthy or not before the dashboard is started, the dashboard could have some extra configuration options to display a message on startup.

Configuration to show a message on startup can display in the existing message UI. Today it's used to display telemetry isn't secured, or max telemetry reached. But it can show multiple messages at once.

**Comment by maddymontaquila** [comment]
My proposal for this as a SUPER short term thing for 9 -

instead of "fail" in the terminal, we show 
"warn": Microsoft.Extensions.<blah>
Hosting failed to start. Please check that your container runtime is started.
<the full error trace>

And instead of not launching the dashboard, we still launch but anything that relies on a container runtime is listed as "Failed to Start" in the dashboard resource view.

9.1+ we could prob do some tooltips in the dashboard, etc

Thoughts??? @davidfowl @mitchdenny @DamianEdwards @JamesNK

**Comment by DamianEdwards** [comment]
Quick hack-up just now on my machine, this is what it looks like after starting TestShop without Docker running: 
![image](https://github.com/user-attachments/assets/df45b536-b671-4191-a0ed-152a43daef6e)
![image](https://github.com/user-attachments/assets/a32eb763-4cb8-460e-b962-d89d796d21fd)

**Comment by DamianEdwards** [comment]
OK a bit more chatting with @davidfowl @karolz-ms and @danegsta just now, here's the proposed click-stops to improve this UX:

1. `Aspire.Hosting` is updated so that when the dashboard is enabled the app host is **not** stopped when a container runtime issue is detected (i.e. the image above). This means if Docker is not running, the dashboard will start but all container-based resources (or resources that are configured to wait for container-based resources) will fail to start. The app host console log and the individual resource console logs will contain the container runtime error message.

    *We should commit to this for 9.0.*

3. DCP is updated (along with any required `Aspire.Hosting` changes) so that container-based resources can be started from the dashboard after they initially failed to start due to a container runtime issue. Right now this is blocked as DCP doesn't recover if the container runtime wasn't healthy when DCP was started but then becomes healthy later. This means the following flow will succeed:
    1. Start the app host when container runtime is stopped
    2. Dashboard appears and shows all container resources in "Failed to start" state
    4. Container runtime is started by the user
    5. Container resources can be started from the dashboard now that the container runtime is running.

*    We will attempt to do this for 9.0, but it might slip to 9.1 depending on how the changes in DCP go.*

3. DCP and `Aspire.Hosting` are updated so that container-based resources will automatically be started once the container runtime becomes healthy if they initially failed to start due to the container runtime being unhealthy at DCP launch. This means the following flow will succeeed:
    1. Start the app host when container runtime is stopped
    2. Dashboard appears and shows all container resources in "Failed to start" state
    4. Container runtime is started by the user
    5. Container resources will automatically start

   *This is the "north star" goal for post-9.0*

**Comment by JamesNK** [comment]
> ![image](https://private-user-images.githubusercontent.com/249088/370838749-90cc5bf1-e065-41cf-9697-69e489eef19a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjQzMzYsIm5iZiI6MTcyNzMyNDAzNiwicGF0aCI6Ii8yNDkwODgvMzcwODM4NzQ5LTkwY2M1YmYxLWUwNjUtNDFjZi05Njk3LTY5ZTQ4OWVlZjE5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNDEzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWIxZDFlNDJmN2E2ZTdhNzdhMjljMzA1Yjg3ZTJmMWNhNTM2YjQxODFhMDFmODcwM2FmMTcyZTE2YWQwMjhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AwfBIGnycgKoJkQGL3e-GjjjL1R7dX1BvWFf3oQ7-wQ)

As well as the error message from connecting to Docker, I'd like the logs to display an extra message that we add. Something as simple as "Failed to connect to Docker. Ensure that Docker is running." would make it clear what is wrong and what they need to do.

**Comment by JamesNK** [comment]
By the way there was a bug that causes these resource logs to be lost. A fix was just checked in to preserve them.

**Comment by davidfowl** [comment]
> As well as the error message from connecting to Docker, I'd like the logs to display an extra message that we add. Something as simple as "Failed to connect to Docker. Ensure that Docker is running." would make it clear what is wrong and what they need to do.

We need to handle multiple container runtimes.

**Comment by DamianEdwards** [comment]
I updated the existing message so that it includes a suggestion to check that the container runtime is running and try again.

**Comment by davidfowl** [comment]
PR up https://github.com/dotnet/aspire/pull/6135
