### ISSUE TITLE
Logs break when restarting projects

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#5803]
Logs for projects are lost after restarting. 

https://github.com/user-attachments/assets/3c7da8f0-b458-46ba-a210-a284522813cc

**Comment by KennethHoff** [comment]
Somewhat unrelated, but that stop button looks like a radio button.

**Comment by afscrome** [comment]
I wonder if this is related to #5626 in that you can't see the logs from the waiting phase of `WaitFor` once the app has started up?

**Comment by davidfowl** [comment]
I spent some time looking at this and it's because we use the same resource name when we restart the resource (by deleting and starting a new one). When we ask DCP for logs, it gives us nothing (which makes sense because it's likely confused about the old log stream).

cc @karolz-ms @danegsta

**Comment by karolz-ms** [comment]
@davidfowl do you see this also happening with the latest DCP version we integrated on Friday 9/20?

We had a bug where if the client asked for logs shortly after the Executable object was created, that request might just result in an empty stream (no error, but no logs ever). This was fixed in the latest DCP release integrated into Aspire.

If the client is recreating the object with the same name, it has to be a bit careful about when it is asking about the logs. The request for the new logs should happen AFTER the new object is created, not "between" old Executable deletion and new Executable creation. Assuming this is the case, DCP should not be confused about the new Executable object with the same name, and a logs request in "follow" mode should result in logs being streamed eventually, even if the logs request comes when the Executable is not fully started. If that is not happening, that is a bug--but we believe we fixed the one we had.

**Comment by davidfowl** [comment]
Yes, the issue is in main.

**Comment by karolz-ms** [comment]
I debugged for a while and I am pretty sure there is some timing issue with the console logs razor page. When I select the Executable from the dropdown to see its logs, I see OnParametersSetAsync() being called, which requests the log stream, but then almost immediately after, DisposeAsync() is called, which calls StopAndClearConstoleLogsSubscriptionAsync(), which cancels the cancellation token associated with the log stream and log capturing stops.

@JamesNK I will let you investigate further; ping me if it turns out to be DCP issue after all.

**Comment by davidfowl** [comment]
Hmm are you sure? I debugger this and didn’t see logs coming out of dcp

**Comment by karolz-ms** [comment]
I am pretty sure. I see DCP being called for logs, but then the associated cancellation token is cancelled. And I verified that calling DCP independently via `kubectl` produces expected logs after restart.

**Comment by JamesNK** [comment]
I looked a bit last night and I think it's a problem with the host as well.

When a resource is deleted, the logs are "completed":

https://github.com/dotnet/aspire/blob/570db520b053ab762f7e713b1b0e3b4632b30cb4/src/Aspire.Hosting/ApplicationModel/ResourceLoggerService.cs#L349-L353

But when the resource is started up again, the CTS is still canceled. Need to add an API to the logger to reset the token when a resource with the same name is recreated.

**Comment by davidfowl** [comment]
Ah I see.

**Comment by davidfowl** [comment]
Moving back to app model
