### ISSUE TITLE
Existing Azure resources can't be used with `AzureFunctionsProjectResource`

### ISSUE THREAD

**Issue by MarcinJuraszek** [dotnet/aspire#6465]
Official [App Host Usage documentation for Service Bus](https://learn.microsoft.com/en-us/dotnet/aspire/messaging/azure-service-bus-integration?tabs=dotnet-cli#app-host-usage) recommends following for creating a Service Bus resource in Aspire AppHost flow:

```
var builder = DistributedApplication.CreateBuilder(args);

var serviceBus = builder.ExecutionContext.IsPublishMode
    ? builder.AddAzureServiceBus("messaging")
    : builder.AddConnectionString("messaging");

builder.AddProject<Projects.ExampleProject>()
       .WithReference(serviceBus)
```

However, because of the ternary operator and usage of `AddConnectionString`, the `serviceBus` variable is typed as `IResourceBuilder<IResourceWithConnectionString>?`. Adding `serviceBus` defined that way to `IResourceBuilder<AzureFunctionsProjectResource>` does not correctly pick up the `IResourceBuilder<AzureFunctionsProjectResource>.WithReference` extension method which means the Service Bus will not be correctly available in the Functions project for Triggers and Bindings.

The same limitation is true for anybody who is using pre-existing Azure resources that are not managed/provisioned by Aspire. Service Bus, Storage, etc. If all you have is a connection string, there's not a way to get that connection string correctly referenced by an `AzureFunctionsProjectResource`.

**Comment by davidfowl** [comment]
Related to https://github.com/dotnet/aspire/issues/2395

**Comment by captainsafia** [comment]
@MarcinJuraszek Thanks for filing this issue!

As @davidfowl tagged above, we think that the right way to resolve this issue is to make our experience for working with pre-provisioned resources a little bit better all-up. In some drive-by conversations, we've proposed an API with a shape like the following:

```csharp
var servicebus = builder.AddAzureServiceBus("messaging").UseExisting(...);
```

That would return an `IResourceBuilder<AzureServiceBus>` that would more nicely plug in with the `IResourceWithAzureFunctionConfig` abstraction to solve the problem that you are running into here. It also gives us the chance to remove the dependency on connection strings as the only strategy for interacting with pre-provisioned resources.

I'm going to close this issue in favor of using the older one to track. We think that this would be a good candidate for a 9.1 item.
