### ISSUE TITLE
Secret handling in app model and inner/outer loop

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#770]
Currently in the app model today we have APIs like this:

```csharp
builder.AddPostgresConnection("inventorydb", "my connection string value");
```

When we publish a manifest we will produce this output:

```json
{
  "resources": {
    "inventorydb": {
      "type": "postgres.connection.v0",
      "connectionString": "my connection string value"
    }
  }
}
```

We need to come up with a mechanism whereby locally we can use a real connection string, but when we create manifests we create empty slots that can be filled in.

Some considerations:

1. Do we model the concept of a secret store (concretely this might be a KeyVault, but might be more abstract)
2. Do we introduce a secret as a first class resource in the app model (or a child resource of the secret store?
3. How does this work with APIs like AddRedisconnection/AddPostgresConnection
4. How does this work with APIs like WithEnvironment
5. How does this work with APIs like WithReference

**Comment by mitchdenny** [comment]
Moving to preview 2 and tagging @samsp-msft  and @davidfowl for thoughts.

**Comment by samsp-msft** [comment]
A couple of thoughts:
- Have an extension `builder.Environment.IsDeploying()` or similar that can be used in the apphost project to control exactly what is created when the deployment manifest is being produced
- The apphost project should *not* pull values from user secrets when producing the deployment manifest. Its ok to pull from appsettings.json, but not user secrets in that scenario. [user secrets should still be used at F5].

**Comment by DamianEdwards** [comment]
Methods like `builder.AddPostgresConnection("inventorydb", "my connection string value");` should have overloads that don't accept a value but rather read the value from the builder configuration using the usual semantics. When the environment is "Development" that includes user secrets and the connection can go there. When publishing a manifest, the environment should likely be the default value ("Production"). Today it's still "Development" because you call `dotnet run` to generate the manifest and that respects the launch profile, which is what sets the environment name. If we move to `dotnet publish` being what generates the manifest, we can control what the environment name is by default. Alternatively, we could add a launch profile to the AppHost project like `generate-manifest` so that one can simply do `dotnet run --launch-profile generate-manifest` to generate the manifest and the environment can be controlled via the settings in that launch profile (which would not set an environment by default, hence resulting in "Production" being the default environment when generating the manifest).

**Comment by danmoseley** [comment]
@mitchdenny I'm guessing this can't happen for preview 2 and you will want to fix the milestone? needs design..

**Comment by dersia** [comment]
we are using ManagedIdentities and Workload Identities today to connect our services to azure services. I think it would be great, if we can have for the manifest a way to define to use a specific ManagedIdentity or a systemAssigned one. but in general, it would make sense when it would have a combination of `endpoint` and `useMI` instead of the connection string, when the manifest is created.

**Comment by davidfowl** [comment]
https://github.com/dotnet/aspire/issues/1958 will replace this issue
