### ISSUE TITLE
Reevaluate all `public` APIs

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/aspire#782]
As a result of generating the .NET Aspire API docs, it became apparent that some APIs should not be `public`. This issue is to track the effort of re-evaluating all .NET Aspire `public` APIs:

- Discuss and determine whether `public` APIs should alter their accessibility modifiers. It's expected that some APIs will become non-`public`, i.e.; `internal`, `protected`, or `private`.
- While working through each API, it might be worthwhile to verify triple slash comments are meaningful, helpful, and provide an acceptable level of detail.

**Comment by IEvangelist** [comment]
For example, this probably shouldn't be `public`:

- [`FileNameSuffixes`](https://learn.microsoft.com/en-us/dotnet/api/aspire.hosting.utils.filenamesuffixes?view=dotnet-aspire-8.0)

**Comment by bart-vmware** [comment]
Is the casing of "EndPoint" within service discovery intentional? I'm asking because it's generally spelled as "Endpoint", for example [here](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.endpointroutingapplicationbuilderextensions.useendpoints?view=aspnetcore-8.0). Also, the [service discovery docs](https://learn.microsoft.com/en-us/dotnet/core/extensions/service-discovery?tabs=dotnet-cli) describe them as "endpoints", not "end-points" or "end points".

**Comment by IEvangelist** [comment]
> Is the casing of "EndPoint" within service discovery intentional? I'm asking because it's generally spelled as "Endpoint", for example [here](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.endpointroutingapplicationbuilderextensions.useendpoints?view=aspnetcore-8.0). Also, the [service discovery docs](https://learn.microsoft.com/en-us/dotnet/core/extensions/service-discovery?tabs=dotnet-cli) describe them as "endpoints", not "end-points" or "end points".

That's a good callout. The various endpoint types are correctly spelled out as `Endpoint`. I think this should be updated, perhaps the old method name should be obsoleted, and the new one with the correct spelling added.

**Comment by mitchdenny** [comment]
In `System.Net` it is `EndPoint` which is probably where our naming came from in service discovery - and then in Aspire we have `EndpointAnnotation`. So we are delightfully inconsistent here.
