### ISSUE TITLE
Enable auto-labeler

### ISSUE THREAD

**Issue by danmoseley** [dotnet/aspire#784]

**Comment by joperezr** [comment]
@RussKie can you please help with this? It would also be great if we can prioritize this sooner rather than later given we are starting to get community issues and we could use help with triaging given we have small windows between previews. @danmoseley shared that when training the model, we should be able to also use the https://github.com/dotnet/aspire-samples repo as well as the internal planning repo in order to better train the bot given we have labels in those too.

**Comment by danmoseley** [comment]
We can also enable it on https://github.com/dotnet/aspire-samples too (ie., train on model on all the repos, deploy same model on aspire and aspire-samples)

**Comment by danmoseley** [comment]
All the issues were already labeled, I spent some time labeling old PR's so it has more material to chew on (it labels PR's too of course)

**Comment by danmoseley** [comment]
This is done, although the poor labeler is somewhat unreliable and we should probably retrain in a month or two . Thanks @RussKie
