### ISSUE TITLE
Add MySQL Aspire Component

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#786]
We will probably have both EF and non-EF components (just like the other database components).

https://www.nuget.org/packages/MySql.EntityFrameworkCore
https://www.nuget.org/packages/MySql.Data

**Comment by bgrainger** [comment]
I am incredibly biased here, since I am the author of MySqlConnector, but I would _strongly_ advocate for https://www.nuget.org/packages/MySqlConnector/ to be the preferred library for MySQL. Some reasons:

1. Better License: MIT instead of GPL
2. OSS development at https://github.com/mysql-net/MySqlConnector; MySql.Data releases code snapshots quarterly but does not have an open development process
3. MySqlConnector supports `DbBatch`, `DbDataSource`, and other new ADO.NET abstractions that have been introduced in recent .NET versions; MySql.Data does not.
4. MySqlConnector has been async-first since the earliest versions; MySql.Data [lacked any async support](https://bugs.mysql.com/bug.php?id=70111) for the last ten years, then shipped with [serious async bugs](https://bugs.mysql.com/bug.php?id=110717) for six months.
5. MySqlConnector has a much more robust suite of integration tests and fewer outstanding known issues.
6. Popularity: the community has recognized the above advantages and MySqlConnector [has more downloads](https://nugettrends.com/packages?months=24&ids=MySql.Data&ids=MySqlConnector) even though it's a newer package.

I'm sure Aspire could have components for both MySqlConnector and MySql.Data, but if it's going to be an "[_opinionated_ stack](https://devblogs.microsoft.com/dotnet/introducing-dotnet-aspire-simplifying-cloud-native-development-with-dotnet-8/)" (emphasis in original), I know which opinion I want it to have. 😀

**Comment by bgrainger** [comment]
7. [AspNetCore.HealthChecks.MySql](https://www.nuget.org/packages/AspNetCore.HealthChecks.MySql) already uses MySqlConnector.

**Comment by eerhardt** [comment]
Re-opening to track adding an EF based component.

**Comment by davidfowl** [comment]
Putting this in preview2 but it'll likely make it for preview3 unless @bgrainger can get this done before next Tuesday 😄

**Comment by bgrainger** [comment]
Per https://github.com/dotnet/aspire/issues/786#issuecomment-1817404908 it's not done, as the MySQL EF Core component (Pomelo) isn't in yet.

**Comment by DamianEdwards** [comment]
I'm assuming the EF Core component is tracking a later preview now?
