### ISSUE TITLE
Add Azure OpenAI Aspire Component

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspire#790]
We should have an Azure OpenAI component. See https://learn.microsoft.com/azure/ai-services/openai/quickstart?pivots=programming-language-csharp

See https://www.nuget.org/packages/Azure.AI.OpenAI/

We should make sure that the Aspire Azure OpenAI Component integrates well with [Semantic Kernel](https://github.com/microsoft/semantic-kernel).

**Comment by justinyoo** [comment]
I've got two use-cases with Azure OpenAI SDK.

1. Azure OpenAI SDK with Azure OpenAI Service

The current Azure OpenAI (AOAI) SDK is less DI-friendly. Here's the plumbing process (as of the version beta-9):

```json
// appsettings.json
{
  ...
  "OpenAI": {
    "Endpoint": "https://xxxxx.openai.azure.com/",
    "ApiKey": "xxxxxxxxxx",
    "DeploymentName": "xxxxxxxxxx"
  }
}
```

```csharp
// Program.cs
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddScoped(sp =>
{
    Uri endpoint = new(Environment.GetVariable("OpenAI__Endpoint"));
    AzureKeyCredential credential = new(Environment.GetVariable("OpenAI__ApiKey"));
    OpenAIClient client = new(endpoint, credential);

    return client;
});

// API controller
public class OpenAIController(OpenAIClient client)
{
    private readonly OpenAIClient _client = client;

    public async Task<string> CompleteAsync(string prompt)
    {
        ChatCompletionsOptions options = new() { ... };
        var result = await this._client.GetChatCompletionsAsync(options);
        ...
    }
}
```

Therefore, in the `AppHost` project, the OpenAI details in the `appsettings.json` file should be passed through `.WithEnvironment(...)` method.

If the `.AddScoped(...)` part is done by the component it would be helpful.

2. Azure OpenAI SDK with Azure OpenAI "Proxy" Service

> **NOTE**: This is a bit hackathon-/workshop-specific scenario, though. As a Cloud Advocacy team, when we run a hackathon or workshop for participants who don't have Azure OpenAI access yet, we provide them with a proxy server endpoint. While the participants still use the Azure OpenAI SDK, we provide the proxy API endpoint and access code so that they can experience Azure OpenAI Service through it.

As mentioned in the option 1, because both API endpoint and key are passed during the start-up process, it's really hard to get the proxy `OpenAIClient` instance, which has the same proxy endpoint URL but random proxy access code.

I know it's not the Aspire issue, but the issue on the SDK itself. But it would be great if both use cases are handled well.

**Comment by sebastienros** [comment]
Current status https://github.com/dotnet/aspire/pull/1475

**Comment by mitchdenny** [comment]
@sebastienros check out #1487 it may be useful in your scenario where you want to reference an Open AI API key.

**Comment by danmoseley** [comment]
#1475 is merged, but it needs attention to how we handle connection string

**Comment by davidfowl** [comment]
@sebastienros Move to P4?

**Comment by eerhardt** [comment]
What is left here? Is this issue only open to track moving from the `ConnectionStrings` config section to some new `ConnectionProperties` section? If so, that should just be tracked with https://github.com/dotnet/aspire/issues/1765. Can this issue be closed?
