### ISSUE TITLE
When `launchUrl` is a full path the dashboard presents a broken link for that service endpoint

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/aspire#812]
The Aspire dashboard presents a link for each service as endpoints

#### How to repro:

- Create a new Aspire Starter Application
- Navigate to the `AspireApp.ApiService\Properties\launchSettings.json` file and make the change below

```diff
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles": {
    "http": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
-      "launchUrl": "weatherforecast",
+      "launchUrl": "http://localhost:5477/weatherforecast",
      "applicationUrl": "http://localhost:5477",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

Notice the difference:

#### When launchUrl is a relative path:
![image](https://github.com/dotnet/aspire/assets/5897654/804f05e3-1c6b-497f-a570-54d2aa600800)

#### When launchUrl is a full path:
- Bug: It is presenting a broken link

![image](https://github.com/dotnet/aspire/assets/5897654/7cb085ce-ef92-49b0-8083-2313fe63fafd)

**Comment by smitpatel** [comment]
We need to see what is behavior in ASP.NET projects. If launch profile handler always appends it or does additional processing if launchUrl contains applicationUrl.

cc: @phenning - Thoughts?

**Comment by DamianEdwards** [comment]
In VS it checks if the URL is absolute or relative and if relative it appends it to the `"applicationUrl"` value, otherwise it uses it as-is. We should do the same in the dashboard.

**Comment by phenning** [comment]
> We need to see what is behavior in ASP.NET projects. If launch profile handler always appends it or does additional processing if launchUrl contains applicationUrl.
> 
> cc: @phenning - Thoughts?

More of a @BillHiebert question.

**Comment by BillHiebert** [comment]
In web projects, and the Aspire App Host app, if the launchUrl is a full URL it just launches it. If it is a relative URL. it is combined with applicationUrl and launches that.

**Comment by smitpatel** [comment]
What @BillHiebert said about url processing in Web projects won't work always for Aspire due to replicas.
A question for @BillHiebert (or anyone else), what if the launchUrl and applicationUrl are not on same website (different base urls, it may not work for single web app)?

For Aspire I propose we show
- Endpoint url if launchUrl is null or empty.
- Endpoint url suffixed with launchUrl if launchUrl is relative.
- Endpoint url replacing the applicationUrl in launchUrl if launchUrl is absolute and applicationUrl is prefix.
- Endpoint url if none of above matches.

If we have launchUrl which is absolute but is not prefixed by applicationUrl so it is not clear how we would combine it with Endpoint url. If endpoint uses same port as application url for single replica scenario, we can just show launchUrl even if not prefix (same as web project hence question for Bill above).

@karolz-ms @DamianEdwards @tlmii - Thoughts?

**Comment by BillHiebert** [comment]
For web projects, the typical pattern is to fill in the applicationUrl,  set launchBrowser to true, and don't set a launchUrl. This launches whatever is in the applicationUrl - ie the root of the site. WebAPi projects will typically have the "swagger" endpoint in launchUrl since the root tends not to be servable. 

@smitpatel  - I don't see why this wouldn't work for replicates. In that case, the DCP should be passing unique port information for each replica and with the above logic, VS will only  update the applicationUrl part of the launchsetting file. So, it should launch the browser on the correct port for each instance.  Though I doubt in practice if you'd want all these browser tabs to open.

Putting a full URL in the launchUrl field was so that you could launch arbitrary URL's when the project launches,

**Comment by smitpatel** [comment]
@BillHiebert - It works for replicas also as long as launchUrl is not arbitrary URL, The moment it becomes arbitrary enough that it is not related to applicationUrl (root of the site), I am not sure what to show for replica at that point. Perhaps it is a case which would never arise.

**Comment by DamianEdwards** [comment]
Maybe we just start out by not supporting arbitrary URL in the dashboard at all.

**Comment by maryamariyan** [comment]
For example, check out this echo-bot sample on [microsoft/teams-ai](https://github.com/microsoft/teams-ai/blob/main/dotnet/samples/01.messaging.echoBot/Properties/launchSettings.json#L4-L12) the launchUrl and applicationUrl are not related.

applicationUrl in this example is teams.microsoft.com and I think if it is not possible to show that in the dashboard then it would be good to know how we could dynamically pick up (get) the applicationUrl value and use it in the webfrontend project for example.

I wonder what you guys think about this use case.

**Comment by DamianEdwards** [comment]
Ah! That's definitely an interesting scenario. Perhaps we need to consider how the UX could be updated to better support the cases where having a launchUrl different to the app/endpoint url is required.

**Comment by maryamariyan** [comment]
> Perhaps we need to consider how the UX could be updated to better support the cases where having a launchUrl different to the app/endpoint url is required.

Created https://github.com/dotnet/aspire/issues/917 to track that.

**Comment by smitpatel** [comment]
With #917 filed, I will implement behavior proposed in https://github.com/dotnet/aspire/issues/812#issuecomment-1815430753
for this issue. Further work when correlation between both URL will be covered in #917 work
