### ISSUE TITLE
warn when Aspire projects opened in Visual Studio 17.8 or earlier?

### ISSUE THREAD

**Issue by danmoseley** [dotnet/aspire#845]
Several people were using 17.8 and expecting debugging to work, but we require 17.9.

@rainersigwald is Visual Studio version available to MSBuild within VS ? I'm guessing not, but if it is, we could just do this in our own packages, perhaps. Similar to when we warn because of targeting and end of life runtime.

**Comment by rainersigwald** [comment]
Not directly but you could probably condition with `'$(BuildingInsideVisualStudio)' == 'true' and $([MSBuild]::VersionGreaterThanOrEquals('$(MSBuildVersion)',  '17.9.0'))`, since we match the VS version in major/minor (at least in customer-facing builds, there's always a few daily builds before our branding-update goes in).

**Comment by danmoseley** [comment]
That would work. @joperezr is there a good place we can put it?

**Comment by joperezr** [comment]
Yeah, we would likely want this to be here: https://github.com/dotnet/aspire/blob/main/src/Aspire.Hosting.Sdk/SDK/Sdk.targets

**Comment by DamianEdwards** [comment]
We should do this in preview 2 as it's an adoption experience issue.
