### ISSUE TITLE
Enable dashboard hosting by PAAS environments

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#888]
The dashboard is highly valuable as a developer-focused, real-time view of what a distributed application is doing and as such it's desirable to have it deployed along with the rest of the resources defined by an AppHost project and configured appropriately for the target environment.

**Comment by samsp-msft** [comment]
Is this just for telemetry or also for control over each of the services. ACA does not currently have a cross-cutting view for all the apps within a container environment or their dependencies. Is that part of what you are looking for here?

**Comment by DamianEdwards** [comment]
I think it can be broken down into the two areas:
- the OpenTelemetry stuff
- the view of Resources

Both are valuable in my mind, but the OTel stuff is likely what most folks are thinking of at this point.

**Comment by davidfowl** [comment]
Building on https://github.com/dotnet/aspire/issues/1003, we should enable deploying the dashboard to various environments (ACA, Kubernetes etc.). That would allow developers to use it as the first line of diagnostics after deployment to see if the application is running properly. The dashboard is a "just in time" diagnostic tool as there is no storage, and it isn't built for massive scale.

Some requirements to make this possible:
- We need to package the dashboard as a container image so that it can be hosted in various environments
- We need to express this in the manifest and describe how it should be interpreted on various environments
- We need to figure out what the view of resource looks like in deployed environments
