### ISSUE TITLE
Show all resources on a single page in the dashboard

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#892]
Today, the dashboard has separate pages for project, container, and executable resources. This makes it cumbersome to see all resources that make up a distributed application being monitored by the dashboard, as one has to click between pages to see the various resource types and their statuses. It also provides nowhere to display custom resource types.

We should consider instead have a single "Resources" page that shows all resources by default, with the ability to filter the view by resource type (one or many). The columns in the table would need to be common enough to apply to all resource types reasonably, e.g. instead of a "project path" column for projects and "base image" for containers it would have a "Details" column that each resource type would use to display the relevant top-level details unique to that resource type. Selecting a row in the table would show the full details for that resource in the details pane, showing whatever fields make sense for the resource type.

**Comment by tlmii** [comment]
> Selecting a row in the table would show the full details for that resource in the details pane, showing whatever fields make sense for the resource type.

One thing to sort out here will be how we handle the extra details (whatever current columns don't fit nicely into the new "details" column) combined with the environment variables. The trace details page's details view has a similar concept already (there are two grids in that details view) so we could potentially start with something like that and then iterate. A true "details" panel (not just a property grid) would probably be more appropriate long term for the first part of that. But that doesn't have to be where we start.

**Comment by smitpatel** [comment]
I think the barebone necessity on single resources page would be to know the state of resources, Running status, any errors, replicas, endpoints. Most of those are kind of common between pages. That would be most useful. There are also other things which my be useful for particular resource kind, may be add those columns only when filtered on that resource kind?

**Comment by DamianEdwards** [comment]
Agreed that the various Id columns could just become unified in a single "Id" column.

One thought is that "Source Location", "Container Image", and "Working Directory" could all be unified into something like a "Location" column? Might be too much of a forced fit though.

Endpoints should for sure be in the default view so that it's easy to click-through to the URLs.

Alternatively we could keep the columns on all the time and just have them be empty (or n/a) for resource types they don't apply to. Perhaps we drop project "Source Location" by default anyway as I'm starting to question its value.

We might want to make the displayed columns configurable in the future (a bit like in Windows Task Manager).

**Comment by berkansasmaz** [comment]
Hello **dotnet team**, if PR is welcome for this issue, I can start working on it. 

If it is suitable for everyone, I can make your improvement suggestions through concrete pages and codes after opening the pull-request.
​
​

**Comment by danmoseley** [comment]
>  "Source Location", "Container Image", and "Working Directory" could all be unified into something like a "Location" column? Might be too much of a forced fit though.

It seems to me it would be fairly self evident what each one is, so a generic Location header would be fine.

**Comment by DamianEdwards** [comment]
@danmoseley maybe "Source" is a better fit?

**Comment by danmoseley** [comment]
That works too.

**Comment by tlmii** [comment]
I took a quick stab at this yesterday so we would have something more visual to react to: 

Added an icon-only column for the type (separate column for sorting). Combined Name, Process Id and Container Id into the Name column. Combined Executable Path + Arguments, Container Image + Ports and Source Location into one Source column. 

eShopLite:
![image](https://github.com/dotnet/aspire/assets/9613109/2de8e9a4-d03c-4dca-a477-40217710545f)

dapr Sample (w/ executables):
![image](https://github.com/dotnet/aspire/assets/9613109/a1bd3b87-3fb7-4100-a3db-4f3675234f57)

There's obviously still some issues here:
1. No good place to put Working Directory. It could go as a second line in Source but it'd likely need to be labeled and that plus the second row makes the layout messier. But it'd work. Or we could move it to the details panel. But so far nothing else had to be moved.
2. Not sure about ports connected to container image that way. Similar to Working Directory above I suppose, but since it is shorter its easier to cram in somewhere
3. In general, it's much harder to visually scan the columns when the data has different meaning per row. So I'm a little worried about the UX here if we do too much mixing things up.
4. We need to come up with a good, easy UI to toggle between All Resources, just Projects, just Containers, just Executables (and possibly some combination of the three). That'll need to be a part of #896 but is also somewhat specific to this page.
5. Lots of general tweaks (e.g. make process id, container id easily copyable again; need icon review; icon-only column has some rendering issues; appropriate tooltips)
