### ISSUE TITLE
Normalize paths in manifest generation

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspire#899]
Currently we use ```\\``` in the manifest, we should standardize on ```/```.

**Comment by BrennanConroy** [comment]
`\` is a valid character in a directory/file on Unix.

For prior-art, the Runtime made a breaking change to remove automatically converting `\\` -> `/`. https://github.com/dotnet/runtime/pull/78995

We could scope the conversion to only occur when creating the manifest on Windows and only when we call `Path` methods since that would always be a valid conversion.

**Comment by davidfowl** [comment]
we want the manifest to always have forward slashes.
