### ISSUE TITLE
Password generated for sql server does not meet SQL Server password policy requirements

### ISSUE THREAD

**Issue by ZieMcd** [dotnet/aspire#971]
When adding SQL server container to distributed app the random password generated for the sa does not meet SQL Server password policy requirements. 

code in Aspire.AppHost project.
`builder.AddSqlServerContainer("sql").AddDatabase("sqldata");`

log output from sql container
```
ERROR: Unable to set system administrator password: Password validation failed. The password does not meet SQL Server password 
policy requirements because it is not complex enough. The password must be at least 8 characters long and contain characters from
three of the following four sets: Uppercase letters, Lowercase letters, Base 10 digits, and Symbols..
```

Current work around is just to pass in your own password like so
`builder.AddSqlServerContainer("sql", "{password}").AddDatabase("sqldata");`

I'm pretty sure the code that generates the password `Guid.NewGuid().ToString("N")` will only contain numbers and letters, no symbols and no Uppercase letters.

**Comment by DamianEdwards** [comment]
Thanks @ZieMcd. Do you mean the default SQL Server password policy, or has it been customized?

**Comment by ZieMcd** [comment]
@DamianEdwards, I am unsure. I don't think I am customizing the password policy as my setup is pretty simple.
In program.cs for the aspire.host project I would have this 
```
var sql = builder.AddSqlServerContainer("sql",).AddDatabase("database");
var apiService = builder.AddProject<My_API>("apiservice")
```
and in program.cs for my api I have this 
```
builder.AddSqlServerDbContext<MyContext>("database");
````
And that's it, not sure how I would alter the password policy.

**Comment by julioct** [comment]
I was just trying this too, very simple setup:

```csharp
var builder = DistributedApplication.CreateBuilder(args);

var sql = builder.AddSqlServerContainer("sql").AddDatabase("GameStore");

var backend = builder.AddProject<Projects.GameStore_Api>("backend")
                     .WithReference(sql);

builder.AddProject<Projects.GameStore_Frontend>("frontend")
       .WithReference(backend);

builder.Build().Run();
```

Same error:
`ERROR: Unable to set system administrator password: Password validation failed. The password does not meet SQL Server password policy requirements because it is not complex enough. The password must be at least 8 characters long and contain characters from three of the following four sets: Uppercase letters, Lowercase letters, Base 10 digits, and Symbols..`

Here's the password that was set by the AppHost, which will not work:

![image](https://github.com/dotnet/aspire/assets/2374270/5da865fb-a279-4d17-8b27-fa289feb7e03)

Can we get a real password there? 

Having to set my own password kind of defeats the purpose of not having to think too much about infra concerns.

**Comment by mitchdenny** [comment]
Yeah this is a straight up bug.
