### ISSUE TITLE
Utilize Azurite For Storage Component

### ISSUE THREAD

**Issue by josephaw1022** [dotnet/aspire#979]
I've noted that the current system offers comprehensive support for various data storage types used in Azure storage accounts. To enhance its capabilities on par with the Redis or Postgres components, I suggest integrating an Azurite component. This addition would enable developers to streamline their workflow without relying exclusively on Azure. I'm interested in understanding the feasibility of this proposal, the steps necessary for its implementation, and the potential changes it would bring to our current setup.

**Comment by davidfowl** [comment]
This already works:

```C#
var blobs = builder.AddAzureStorage("storage")
                   .UseEmulator()
                   .AddBlobs("blobs");
```

**Comment by davidfowl** [comment]
cc @IEvangelist

**Comment by peteraritchie** [comment]
> ```cs
> var blobs = builder.AddAzureStorage("storage")
>                    .UseEmulator()
>                    .AddBlobs("blobs");
> ```

@davidfowl Is it expected that in a "development" only environment that the emulator would be used like this:?

```cs
var blobs = builder.AddAzureStorage("storage")
#if DEBUG
                   .UseEmulator()
#endif
                   .AddBlobs("blobs");
```

Or more like this:?
```cs
var storage = builder.AddAzureStorage("storage");
if(builder.Environment.IsDevelopment())
{
 	storage = storage.UseEmulator();
}
var blobs = storage.AddBlobs("blobs");
```

**Comment by IEvangelist** [comment]
I think we can close this issue, it's now in the .NET Aspire docs:

https://learn.microsoft.com/dotnet/aspire/storage/azure-storage?pivots=azurite

![image](https://github.com/dotnet/aspire/assets/7679720/1e4cca1e-02b7-44a3-81bd-51d9f6afeead)

**Comment by peteraritchie** [comment]
> I would ask why you were trying to accomplish with the latter suggestions?

My question may be a little unrelated, apologies @davidfowl  Although, I think I found my answer here:  https://github.com/dotnet/docs-aspire/blob/main/docs/storage/snippets/tutorial/AspireStorage/AspireStorage.AppHost/Program.cs#L7.

**Comment by Dona278** [comment]
How about the possibility of the use of a single connection string with all three endpoints in case of `.UseEmulator()`?

Since the born of the storage emulator it was possible to use azure storage SDK clients (queue, table and blobs) with only one connection string declared in the format: `AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:{blobPort}/devstoreaccount1;QueueEndpoint=http://127.0.0.1:{queuePort}/devstoreaccount1;TableEndpoint=http://127.0.0.1:{tablePort}/devstoreaccount1;`. 

So it was possible the use of a single connection string, (e.g. `IdentityStorage`) in `appsettings.json` but now with Aspire we have to call .AddBlobs()`, `.AddQueues()` and `.AddTables()` which lead to three connection strings injected with different names.

I'm sorry if I missed something and I'm wrong..

**Comment by davidfowl** [comment]
You can use a single connection string with the aspire APIs

**Comment by philliphoff** [comment]
@Dona278 I just ran into scenario where I need the same thing--a single connection string that contains all three endpoints rather than three separate blob/queue/table connection strings.  I've added a proposal (#1727) to provide the option of a combined connection string.

**Comment by Dona278** [comment]
@philliphoff I've made the same changes in local by inherith the current AzureStorageResource to avoid an identical component copied/pasted with only the interface added to handle connectionstring. So in case thank you!

**Comment by danmoseley** [comment]
@josephaw1022 Can we close now?

**Comment by josephaw1022** [comment]
@danmoseley Yeah I can close it. I think this was and is in a good enough spot.
